In [ ]:
!pip install -q pdfplumber tqdm

In [ ]:


import pdfplumber
import sqlite3
import pandas as pd
import re
import os
from tqdm import tqdm

PDF_PATH = "/content/co-ursi-key-regultry-parmtrs-pwr-utiltis-dt180526.pdf"

DB_PATH = "pdf_index.db"
CSV_PATH = "page_index.csv"


TABLE_REGEX = re.compile(
    r"(TABLE[- ]?\d+(?:\([A-Z]\))?\s*:\s*[^\n]+)",
    flags=re.IGNORECASE
)


def detect_tables(text):

    matches = TABLE_REGEX.findall(text)

    cleaned = []

    for m in matches:

        m = re.sub(r"\s+", " ", m).strip()

        if len(m) > 8:
            cleaned.append(m)

    return sorted(list(set(cleaned)))


if os.path.exists(DB_PATH):
    os.remove(DB_PATH)

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()


cur.execute("""
CREATE TABLE page_index (

    page_number INTEGER PRIMARY KEY,

    page_text TEXT,

    table_titles TEXT,

    contains_table INTEGER,

    text_length INTEGER
)
""")


cur.execute("""
CREATE VIRTUAL TABLE page_search
USING fts5(

    page_text,

    table_titles,

    content=''

)
""")

conn.commit()


rows = []

with pdfplumber.open(PDF_PATH) as pdf:

    total_pages = len(pdf.pages)

    print("="*70)
    print("PDF INFORMATION")
    print("="*70)

    print("Total Pages :", total_pages)

    for page_idx in tqdm(range(total_pages)):

        page = pdf.pages[page_idx]

        try:
            text = page.extract_text() or ""
        except:
            text = ""

        tables = detect_tables(text)

        table_text = " | ".join(tables)

        contains_table = 1 if len(tables) > 0 else 0

        rows.append({

            "page_number": page_idx + 1,
            "table_titles": table_text,
            "contains_table": contains_table,
            "text_length": len(text),
            "page_text": text
        })


df = pd.DataFrame(rows)


for _, row in df.iterrows():

    cur.execute(
        """
        INSERT INTO page_index
        VALUES(?,?,?,?,?)
        """,
        (
            int(row.page_number),
            row.page_text,
            row.table_titles,
            int(row.contains_table),
            int(row.text_length)
        )
    )

    cur.execute(
        """
        INSERT INTO page_search
        (
            page_text,
            table_titles
        )
        VALUES (?,?)
        """,
        (
            row.page_text,
            row.table_titles
        )
    )

conn.commit()


df.to_csv(CSV_PATH, index=False)


print()
print("="*70)
print("INDEX CREATED")
print("="*70)

print("Pages Indexed :", len(df))
print("Pages With Tables :", int(df.contains_table.sum()))


print()
print("="*70)
print("TABLE PAGES")
print("="*70)

display(

    df[
        df.contains_table == 1
    ][
        [
            "page_number",
            "table_titles"
        ]
    ].head(50)

)


print()
print("="*70)
print("FTS5 SEARCH TESTS")
print("="*70)

queries = [

    "open access",
    "cross subsidy surcharge",
    "wheeling charge",
    "transmission charge",
    "banking charges"

]

for q in queries:

    results = cur.execute(
        """
        SELECT rowid
        FROM page_search
        WHERE page_search MATCH ?
        LIMIT 20
        """,
        (q,)
    ).fetchall()

    pages = [r[0] for r in results]

    print()
    print("QUERY :", q)
    print("PAGES :", pages)


print()
print("="*70)
print("OPEN ACCESS REGION")
print("="*70)

display(

    df[
        (df.page_number >= 49)
        &
        (df.page_number <= 65)
    ][
        [
            "page_number",
            "table_titles",
            "contains_table"
        ]
    ]

)


print()
print("="*70)
print("FILES")
print("="*70)

print(
    "SQLite:",
    round(
        os.path.getsize(DB_PATH)/(1024*1024),
        2
    ),
    "MB"
)

print(
    "CSV:",
    round(
        os.path.getsize(CSV_PATH)/(1024*1024),
        2
    ),
    "MB"
)

conn.close()

======================================================================
PDF INFORMATION
======================================================================
Total Pages : 294

100%|██████████| 294/294 [01:06<00:00,  4.45it/s]

======================================================================
INDEX CREATED
======================================================================
Pages Indexed : 294
Pages With Tables : 32

======================================================================
TABLE PAGES
======================================================================

     page_number                                       table_titles
4              5  TABLE-1(A) : TARIFF ORDER FOR FY-27 AND TRUE U...
5              6  TABLE-1: TRAJECTORY FOR AT&C LOSS UNDER RDSS ....
31            32  Table-2(a): Domestic Category (3 Kilo Watt, 10...
33            34  Table-2(b): Domestic Category (3 Kilo Watt, 50...
35            36  Table-2(c): Non-Domestic Category (5 Kilo Watt...
37            38  Table-2(d): Agriculture Category (7.5 Kilo Wat...
39            40  Table-2(e): Small Industrial Category (10 Kilo...
41            42  Table-2(f): Medium Industrial Category (50 Kil...
43            44  Table-2(g): Large Industrial Category (1000 Ki...
45            46  Table-3: Cross Subsidy and Consumption Trend f...
47            48  Table-4: Cross Subsidy and Consumption Trend f...
49            50  Table-5(a): Cross Subsidy Surcharge | Table-5:...
56            57                   Table-5(b): Additional Surcharge
58            59                        Table-5(c): Wheeling Charge
61            62                    Table-5(d): Transmission Charge
63            64                        Table-5(e): Banking Charges
75            76  Table-6: Applicability of Time of Day (ToD) Ta...
80            81  Table-7(a): RoE-Generation Utilities | Table-7...
83            84             Table-7(b): RoE-Transmission Utilities
85            86             Table-7(c): RoE-Distribution Utilities
88            89               Table-8: Number of Pending Petitions
90            91  Table-9: Alignment of Electricity (Rights of C...
93            94  Table-10(a): Automatic Adjustment of Fuel and ...
95            96  Table-10(b): Fuel and Power Purchase Cost Adju...
99           100       Table-11: Revenue Gap creation & Liquidation
101          102    Table-12: Financial Disallowance by SERCs/JERCs
105          106                    Table-13: Reliability of Supply
111          112    Table-14: Grid Interactive Rooftop Solar system
117          118  Table-15: Green Energy Open Access (GEOA) Regu...
119          120  Table-16: Status of Standard of Performance (S...
284          285  Table-1: Trajectory for AT&C loss for FY 2021-...
286          287  Table-2: Trajectory for ACS-ARR for FY 2021-22...

======================================================================
FTS5 SEARCH TESTS
======================================================================

QUERY : open access
PAGES : [5, 14, 17, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 74]

QUERY : cross subsidy surcharge
PAGES : [5, 14, 50, 56, 157, 162, 243, 251, 265, 290]

QUERY : wheeling charge
PAGES : [5, 14, 59]

QUERY : transmission charge
PAGES : [5, 14, 62, 145, 153, 175, 194, 252, 283]

QUERY : banking charges
PAGES : [5, 50, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75]

======================================================================
OPEN ACCESS REGION
======================================================================

,page_number,table_titles,contains_table
48,49,,0
49,50,Table-5(a): Cross Subsidy Surcharge | Table-5:...,1
50,51,,0
51,52,,0
52,53,,0
53,54,,0
54,55,,0
55,56,,0
56,57,Table-5(b): Additional Surcharge,1
57,58,,0
58,59,Table-5(c): Wheeling Charge,1
59,60,,0
60,61,,0
61,62,Table-5(d): Transmission Charge,1
62,63,,0
63,64,Table-5(e): Banking Charges,1
64,65,,0

======================================================================
FILES
======================================================================
SQLite: 1.1 MB
CSV: 0.67 MB

In [ ]:


import pandas as pd
import json

CSV_PATH = "page_index.csv"

df = pd.read_csv(CSV_PATH)


table_pages = df[
    (df["contains_table"] == 1) &
    (df["page_number"] >= 20)
].copy()

table_pages = table_pages.sort_values(
    "page_number"
)



catalog = []

for _, row in table_pages.iterrows():

    page = int(row["page_number"])

    titles = str(row["table_titles"])

    for title in titles.split("|"):

        title = title.strip()

        if len(title) < 5:
            continue

        catalog.append({
            "page": page,
            "title": title
        })

catalog_df = pd.DataFrame(catalog)


anchors = sorted(
    table_pages["page_number"].tolist()
)

def get_section(start_page):

    idx = anchors.index(start_page)

    if idx == len(anchors) - 1:

        end_page = int(df.page_number.max())

    else:

        end_page = anchors[idx + 1] - 1

    return list(
        range(start_page, end_page + 1)
    )


SEARCH_MAP = {

    "open access":
        "open access",

    "cross subsidy surcharge":
        "cross subsidy surcharge",

    "additional surcharge":
        "additional surcharge",

    "wheeling charge":
        "wheeling charge",

    "transmission charge":
        "transmission charge",

    "banking charges":
        "banking charges",

    "tod":
        "tod",

    "return on equity":
        "return on equity",

    "pending petitions":
        "pending petitions",

    "reliability":
        "reliability"
}


def find_relevant_pages(query):

    q = query.lower()

    keyword = None

    for k in SEARCH_MAP:

        if k in q:
            keyword = SEARCH_MAP[k]
            break

    if keyword is None:

        return {
            "success": False,
            "message": "keyword not found"
        }

    hits = catalog_df[
        catalog_df["title"]
        .str.contains(
            keyword,
            case=False,
            na=False
        )
    ]

    if len(hits) == 0:

        return {
            "success": False,
            "message": "table not found"
        }

    hit = hits.iloc[0]

    page = int(hit["page"])

    pages = get_section(page)

    return {

        "success": True,

        "query": query,

        "matched_table":
            hit["title"],

        "section_start":
            pages[0],

        "section_end":
            pages[-1],

        "pages":
            pages
    }


tests = [

    "Extract Open Access Charges",

    "Extract Cross Subsidy Surcharge",

    "Extract Additional Surcharge",

    "Extract Wheeling Charge",

    "Extract Transmission Charge",

    "Extract Banking Charges"
]

print("="*70)
print("PHASE 2.3 TESTS")
print("="*70)

for t in tests:

    print()
    print(
        json.dumps(
            find_relevant_pages(t),
            indent=2
        )
    )

======================================================================
PHASE 2.3 TESTS
======================================================================

{
  "success": true,
  "query": "Extract Open Access Charges",
  "matched_table": "Table-5: Open Access Charges",
  "section_start": 50,
  "section_end": 56,
  "pages": [
    50,
    51,
    52,
    53,
    54,
    55,
    56
  ]
}

{
  "success": true,
  "query": "Extract Cross Subsidy Surcharge",
  "matched_table": "Table-5(a): Cross Subsidy Surcharge",
  "section_start": 50,
  "section_end": 56,
  "pages": [
    50,
    51,
    52,
    53,
    54,
    55,
    56
  ]
}

{
  "success": true,
  "query": "Extract Additional Surcharge",
  "matched_table": "Table-5(b): Additional Surcharge",
  "section_start": 57,
  "section_end": 58,
  "pages": [
    57,
    58
  ]
}

{
  "success": true,
  "query": "Extract Wheeling Charge",
  "matched_table": "Table-5(c): Wheeling Charge",
  "section_start": 59,
  "section_end": 61,
  "pages": [
    59,
    60,
    61
  ]
}

{
  "success": true,
  "query": "Extract Transmission Charge",
  "matched_table": "Table-5(d): Transmission Charge",
  "section_start": 62,
  "section_end": 63,
  "pages": [
    62,
    63
  ]
}

{
  "success": true,
  "query": "Extract Banking Charges",
  "matched_table": "Table-5(e): Banking Charges",
  "section_start": 64,
  "section_end": 75,
  "pages": [
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75
  ]
}

In [ ]:
# import pandas as pd

# df = pd.read_csv("page_index.csv")

# for _, row in df[df["contains_table"] == 1].iterrows():

#     print("\nPAGE:", row["page_number"])
#     print(row["table_titles"][:500])
#     print("-"*80)

PAGE: 5
TABLE-1(A) : TARIFF ORDER FOR FY-27 AND TRUE UP ORDER FOR FY-25 FOR DISTRIBUTION UTILITIES .................... 22 | TABLE-1(B) : ISSUANCE OF MULTI YEAR TARIFF (MYT) ORDER ................................................................................. 29 | TABLE-10(A) : AUTOMATIC ADJUSTMENT OF FUEL AND POWER PURCHASE COST- COMPLIANCE STATUS AT SERC/JERC | TABLE-10(B) : AUTOMATIC ADJUSTMENT OF FUEL AND POWER PURCHASE COST- COMPLIANCE STATUS AT DISCOMS | TABLE-11: REVENUE GAP CREATION AND LIQUID
--------------------------------------------------------------------------------

PAGE: 6
TABLE-1: TRAJECTORY FOR AT&C LOSS UNDER RDSS ............................................................................................ 284 | TABLE-2: TRAJECTORY FOR ACS-ARR GAP UNDER RDSS ....................................................................................... 286
--------------------------------------------------------------------------------

PAGE: 32
Table-2(a): Domestic Category (3 Kilo Watt, 100 Units per month) | Table-2: Category wise comparison of Representative Tariffs
--------------------------------------------------------------------------------

PAGE: 34
Table-2(b): Domestic Category (3 Kilo Watt, 500 Units per month)
--------------------------------------------------------------------------------

PAGE: 36
Table-2(c): Non-Domestic Category (5 Kilo Watt, 500 Units per month)
--------------------------------------------------------------------------------

PAGE: 38
Table-2(d): Agriculture Category (7.5 Kilo Watt, 15% Load Factor, 817 Units per month)
--------------------------------------------------------------------------------

PAGE: 40
Table-2(e): Small Industrial Category (10 Kilo Watt 20%, Load Factor, 1460 Units per month)
--------------------------------------------------------------------------------

PAGE: 42
Table-2(f): Medium Industrial Category (50 Kilo Watt 30%, Load Factor, 10950 Units per
--------------------------------------------------------------------------------

PAGE: 44
Table-2(g): Large Industrial Category (1000 Kilo Watt 40% Load Factor, 365000 Units per
--------------------------------------------------------------------------------

PAGE: 46
Table-3: Cross Subsidy and Consumption Trend for LT Industrial Consumers
--------------------------------------------------------------------------------

PAGE: 48
Table-4: Cross Subsidy and Consumption Trend for HT Industrial Consumers
--------------------------------------------------------------------------------

PAGE: 50
Table-5(a): Cross Subsidy Surcharge | Table-5: Open Access Charges
--------------------------------------------------------------------------------

PAGE: 57
Table-5(b): Additional Surcharge
--------------------------------------------------------------------------------

PAGE: 59
Table-5(c): Wheeling Charge
--------------------------------------------------------------------------------

PAGE: 62
Table-5(d): Transmission Charge
--------------------------------------------------------------------------------

PAGE: 64
Table-5(e): Banking Charges
--------------------------------------------------------------------------------

PAGE: 76
Table-6: Applicability of Time of Day (ToD) Tariff
--------------------------------------------------------------------------------

PAGE: 81
Table-7(a): RoE-Generation Utilities | Table-7: Return on Equity
--------------------------------------------------------------------------------

PAGE: 84
Table-7(b): RoE-Transmission Utilities
--------------------------------------------------------------------------------

PAGE: 86
Table-7(c): RoE-Distribution Utilities
--------------------------------------------------------------------------------

PAGE: 89
Table-8: Number of Pending Petitions
--------------------------------------------------------------------------------

PAGE: 91
Table-9: Alignment of Electricity (Rights of Consumers) Rules 2020
--------------------------------------------------------------------------------

PAGE: 94
Table-10(a): Automatic Adjustment of Fuel and Power Purchase Costs- Compliance
--------------------------------------------------------------------------------

PAGE: 96
Table-10(b): Fuel and Power Purchase Cost Adjustments-Compliance Status of DISCOMs
--------------------------------------------------------------------------------

PAGE: 100
Table-11: Revenue Gap creation & Liquidation
--------------------------------------------------------------------------------

PAGE: 102
Table-12: Financial Disallowance by SERCs/JERCs
--------------------------------------------------------------------------------

PAGE: 106
Table-13: Reliability of Supply
--------------------------------------------------------------------------------

PAGE: 112
Table-14: Grid Interactive Rooftop Solar system
--------------------------------------------------------------------------------

PAGE: 118
Table-15: Green Energy Open Access (GEOA) Regulation implementation
--------------------------------------------------------------------------------

PAGE: 120
Table-16: Status of Standard of Performance (SOP) and Compensation Mechanism
--------------------------------------------------------------------------------

PAGE: 285
Table-1: Trajectory for AT&C loss for FY 2021-22 to FY 2025-26 under RDSS
--------------------------------------------------------------------------------

PAGE: 287
Table-2: Trajectory for ACS-ARR for FY 2021-22 to FY 2025-26 under RDSS
--------------------------------------------------------------------------------

In [ ]:
# import pandas as pd

# df = pd.read_csv("page_index.csv")

# table_pages = df[df["contains_table"] == 1]

# table_pages = table_pages[
#     table_pages["page_number"] >= 20
# ]

# print(
#     table_pages[
#         ["page_number","table_titles"]
#     ]
# )

     page_number                                       table_titles
31            32  Table-2(a): Domestic Category (3 Kilo Watt, 10...
33            34  Table-2(b): Domestic Category (3 Kilo Watt, 50...
35            36  Table-2(c): Non-Domestic Category (5 Kilo Watt...
37            38  Table-2(d): Agriculture Category (7.5 Kilo Wat...
39            40  Table-2(e): Small Industrial Category (10 Kilo...
41            42  Table-2(f): Medium Industrial Category (50 Kil...
43            44  Table-2(g): Large Industrial Category (1000 Ki...
45            46  Table-3: Cross Subsidy and Consumption Trend f...
47            48  Table-4: Cross Subsidy and Consumption Trend f...
49            50  Table-5(a): Cross Subsidy Surcharge | Table-5:...
56            57                   Table-5(b): Additional Surcharge
58            59                        Table-5(c): Wheeling Charge
61            62                    Table-5(d): Transmission Charge
63            64                        Table-5(e): Banking Charges
75            76  Table-6: Applicability of Time of Day (ToD) Ta...
80            81  Table-7(a): RoE-Generation Utilities | Table-7...
83            84             Table-7(b): RoE-Transmission Utilities
85            86             Table-7(c): RoE-Distribution Utilities
88            89               Table-8: Number of Pending Petitions
90            91  Table-9: Alignment of Electricity (Rights of C...
93            94  Table-10(a): Automatic Adjustment of Fuel and ...
95            96  Table-10(b): Fuel and Power Purchase Cost Adju...
99           100       Table-11: Revenue Gap creation & Liquidation
101          102    Table-12: Financial Disallowance by SERCs/JERCs
105          106                    Table-13: Reliability of Supply
111          112    Table-14: Grid Interactive Rooftop Solar system
117          118  Table-15: Green Energy Open Access (GEOA) Regu...
119          120  Table-16: Status of Standard of Performance (S...
284          285  Table-1: Trajectory for AT&C loss for FY 2021-...
286          287  Table-2: Trajectory for ACS-ARR for FY 2021-22...

In [ ]:
!apt-get -qq install poppler-utils > /dev/null
!pip install -q pdf2image opencv-python-headless pillow pandas

In [ ]:

# !apt-get -qq install poppler-utils > /dev/null
# !pip install -q pdf2image opencv-python-headless pillow pandas

import cv2
import numpy as np
import pandas as pd

from pdf2image import convert_from_path


PDF_PATH = "/content/co-ursi-key-regultry-parmtrs-pwr-utiltis-dt180526.pdf"

# Candidate pages from Phase 2
CANDIDATE_PAGES = [
    50,51,52,53,54,55,56
]

print("="*70)
print("RENDERING PAGES")
print("="*70)

images = convert_from_path(

    PDF_PATH,

    dpi=200,

    first_page=min(CANDIDATE_PAGES),

    last_page=max(CANDIDATE_PAGES)
)


def detect_table(image):

    gray = cv2.cvtColor(
        np.array(image),
        cv2.COLOR_RGB2GRAY
    )

    thresh = cv2.adaptiveThreshold(

        gray,

        255,

        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,

        cv2.THRESH_BINARY_INV,

        15,

        4
    )


    horizontal_kernel = cv2.getStructuringElement(

        cv2.MORPH_RECT,

        (40,1)
    )

    horizontal = cv2.morphologyEx(

        thresh,

        cv2.MORPH_OPEN,

        horizontal_kernel
    )



    vertical_kernel = cv2.getStructuringElement(

        cv2.MORPH_RECT,

        (1,40)
    )

    vertical = cv2.morphologyEx(

        thresh,

        cv2.MORPH_OPEN,

        vertical_kernel
    )



    h_cnts, _ = cv2.findContours(

        horizontal,

        cv2.RETR_EXTERNAL,

        cv2.CHAIN_APPROX_SIMPLE
    )

    v_cnts, _ = cv2.findContours(

        vertical,

        cv2.RETR_EXTERNAL,

        cv2.CHAIN_APPROX_SIMPLE
    )



    grid = cv2.add(
        horizontal,
        vertical
    )

    contours, _ = cv2.findContours(

        grid,

        cv2.RETR_EXTERNAL,

        cv2.CHAIN_APPROX_SIMPLE
    )

    rect_count = 0

    for c in contours:

        x,y,w,h = cv2.boundingRect(c)

        area = w*h

        if area > 20000:
            rect_count += 1


    score = (

        min(len(h_cnts),50)/50 * 0.4 +

        min(len(v_cnts),50)/50 * 0.4 +

        min(rect_count,10)/10 * 0.2
    )

    contains_table = score > 0.20

    return {

        "horizontal_lines":
            len(h_cnts),

        "vertical_lines":
            len(v_cnts),

        "large_rectangles":
            rect_count,

        "table_score":
            round(score,3),

        "contains_table":
            contains_table
    }


results = []

for page_num, image in zip(
    CANDIDATE_PAGES,
    images
):

    result = detect_table(image)

    result["page"] = page_num

    results.append(result)



results_df = pd.DataFrame(results)

print()
print("="*70)
print("TABLE DETECTION RESULTS")
print("="*70)

display(results_df)


table_pages = results_df[
    results_df["contains_table"] == True
]

print()
print("="*70)
print("PAGES SENT TO OCR")
print("="*70)

print(
    table_pages["page"].tolist()
)

======================================================================
RENDERING PAGES
======================================================================

======================================================================
TABLE DETECTION RESULTS
======================================================================

,horizontal_lines,vertical_lines,large_rectangles,table_score,contains_table,page
0,122,12,1,0.516,True,50
1,150,37,4,0.776,True,51
2,166,42,6,0.856,True,52
3,116,19,4,0.632,True,53
4,145,29,7,0.772,True,54
5,118,25,5,0.700,True,55
6,24,4,1,0.244,True,56

======================================================================
PAGES SENT TO OCR
======================================================================
[50, 51, 52, 53, 54, 55, 56]

In [ ]:
OUTPUT_CSV_PATH = "table_detection_results.csv"
results_df.to_csv(OUTPUT_CSV_PATH, index=False)
print(f"Table detection results saved to {OUTPUT_CSV_PATH}")

Table detection results saved to table_detection_results.csv

In [ ]:

import pdfplumber
import pandas as pd
import json


PDF_PATH = "/content/co-ursi-key-regultry-parmtrs-pwr-utiltis-dt180526.pdf"

CANDIDATE_PAGES = [
    50,51,52,53,54,55
]


results = []

with pdfplumber.open(PDF_PATH) as pdf:

    for page_num in CANDIDATE_PAGES:

        page = pdf.pages[page_num - 1]

        try:

            tables = page.extract_tables()

        except Exception as e:

            print(
                f"Page {page_num} failed:",
                e
            )

            continue

        page_result = {

            "page": page_num,

            "extractor": "pdfplumber",

            "table_count": len(tables),

            "tables": []
        }



        for idx, table in enumerate(tables):

            cleaned = []

            for row in table:

                if row is None:
                    continue

                cleaned_row = []

                for cell in row:

                    if cell is None:
                        cleaned_row.append("")
                    else:
                        cleaned_row.append(
                            str(cell).strip()
                        )

                cleaned.append(cleaned_row)

            page_result["tables"].append({

                "table_id": idx + 1,

                "rows": cleaned,

                "n_rows": len(cleaned),

                "n_cols": max(
                    [len(r) for r in cleaned],
                    default=0
                )
            })

        results.append(page_result)


print("="*80)
print("TABLE EXTRACTION SUMMARY")
print("="*80)

for page in results:

    print()

    print(
        f"Page {page['page']}"
    )

    print(
        f"Tables: {page['table_count']}"
    )

    for t in page["tables"]:

        print(
            f"  Table {t['table_id']} "
            f"({t['n_rows']} x {t['n_cols']})"
        )

with open(
    "phase4_tables.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        results,
        f,
        ensure_ascii=False,
        indent=2
    )

print()
print("="*80)
print("SAVED")
print("="*80)
print("phase4_tables.json")

================================================================================
TABLE EXTRACTION SUMMARY
================================================================================

Page 50
Tables: 1
  Table 1 (25 x 12)

Page 51
Tables: 1
  Table 1 (57 x 16)

Page 52
Tables: 1
  Table 1 (58 x 21)

Page 53
Tables: 1
  Table 1 (56 x 14)

Page 54
Tables: 1
  Table 1 (54 x 21)

Page 55
Tables: 1
  Table 1 (58 x 19)

================================================================================
SAVED
================================================================================
phase4_tables.json

In [ ]:
import json

with open(
    "phase4_tables.json",
    "r",
    encoding="utf-8"
) as f:

    data = json.load(f)

for page in data:

    print("\n")
    print("="*100)
    print("PAGE", page["page"])
    print("="*100)

    for table in page["tables"]:

        print("\nTABLE", table["table_id"])

        df = pd.DataFrame(
            table["rows"]
        )

        display(df.head(15))

====================================================================================================
PAGE 50
====================================================================================================

TABLE 1

,0,1,2,3,4,5,6,7,8,9,10,11
0,,आं(cid:364) (cid:366)देश / Andhra Pradesh,,,2026-27,,,,,,,
1,,Category,,,APSPDCL,,,APEPDCL,,,APCPDCL,
2,,HT Category at 11 kV,,,,,,,,,,
3,"HT I(B) Townships, Colonies, Gated\nCommunitie...",,,0.97,,,0.89,,,1.12,,
4,HT II (A) Commercial& Others,,,2.09,,,2.20,,,2.32,,
5,HT II (A) Function Halls/ Auditoriums,,,1.99,,,1.99,,,1.99,,
6,HT II (B) Start-up power,,,1.99,,,1.99,,,-,,
7,HT III(A) Industry,,,1.89,,,1.71,,,1.85,,
8,HT III(B) Seasonal Industries (Off Season),,,2.38,,,1.76,,,1.74,,
9,HT III (C ) Energy Intensive Industries,,,1.58,,,-,,,1.75,,
10,HT IV (A) Utilities (Composite Protected Water...,,,1.86,,,1.91,,,1.80,,
11,HT IV (B) General Purpose,,,2.28,,,2.25,,,2.13,,
12,HT V (E ) Government/ Private Lift Irrigation,,,-,,,0.56,,,0.57,,
13,,HT Category at 33 kV,,,,,,,,,,
14,"HT I(B) Townships, Colonies, Gated\nCommunitie...",,,1.52,,,1.47,,,1.50,,

====================================================================================================
PAGE 51
====================================================================================================

TABLE 1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,HT II(B) Start Up Power,,,1.99,,,1.99,,,,,,,1.99,,
1,HT III(A) Industry,,,1.37,,,1.44,,,,,,,1.40,,
2,HT III(C ) Energy Intensive Industry,,,0.31,,,0.51,,,,,,,-,,
3,HT IV(D) Railway Traction,,,1.63,,,1.59,,,,,,,1.56,,
4,HT V (E ),,,1.43,,,-,,,,,,,1.43,,
5,,220 kV,,,,,,,,,,,,,,
6,HT II(A) Commercial & Others,,,-,,,1.66,,,,,,,-,,
7,HT II(B) Start up Power,,,1.99,,,1.99,,,,,,,-,,
8,HT III(A) Industry,,,1.57,,,1.37,,,,,,,1.96,,
9,HT III (C ) Energy Intensive Industries,,,-,,,1.57,,,,,,,-,,
10,HT IV(D) Railway Traction,,,1.66,,,-,,,,,,,-,,
11,HT V (E ) Government/ Private Lift Irrigation,,,1.43,,,1.43,,,,,,,-,,
12,,असम / Assam,,,2026-27,,,,,,,,,,,
13,,Category,,,APDCL,,,,,,,,,,,
14,HT Domestic and Commercial 30 kW & above,,,1.81,,,,,,,,,,,,

====================================================================================================
PAGE 52
====================================================================================================

TABLE 1

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,गोवा / Goa,,,,2026-27,,,,,,...,,,,,,,,,,
1,,Category,,,"Electricity Department, Goa (EDG)",,,,,,...,,,,,,,,,,
2,Low Tension (LT) Level,,,NIL,,,,,,,...,,,,,,,,,,
3,High Tension (HT)/ EHT Level,,,1.13,,,,,,,...,,,,,,,,,,
4,Extra High Tension (EHT) Level,,,0.68,,,,,,,...,,,,,,,,,,
5,गुजरात / Gujarat,,,2026-27,,,,,,,...,,,,,,,,,,
6,,Category,,,DGVCL,,,PGVCL,,,...,,,,,,UGVCL,,,,
7,HT Category,,,1.33,,,1.33,,,1.33,...,,,,,1.33,,,,,
8,ह(cid:303)रयाणा / Haryana,,,,2026-27,,,,,,...,,,,,,,,,,
9,,Category,,,UHBVNL,,,,,,...,,,DHBVNL,,,,,,,
10,HT Supply,,,,1.45,,,,,,...,,,1.45,,,,,,,
11,Bulk Supply (other than DS),,,,-,,,,,,...,,,-,,,,,,,
12,LT Supply,,,,1.18,,,,,,...,,,1.18,,,,,,,
13,,िहमाचल (cid:366)देश / Himachal Pradesh,,,2026-27,,,,,,...,,,,,,,,,,
14,Category,,,HPSEBL,,,,,,,...,,,,,,,,,,

====================================================================================================
PAGE 53
====================================================================================================

TABLE 1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,LT-3b,,,3.05,,3.05,,3.05,,,3.05,,3.05,
1,LT-4a,,,0.49,,0.49,,0.49,,,0.49,,0.49,
2,LT-4b,,,1.07,,1.07,,1.07,,,1.07,,1.07,
3,LT-4c,,,1.85,,1.85,,1.85,,,1.85,,1.85,
4,LT-5 Industrial,,,1.16,,1.16,,1.16,,,1.16,,1.16,
5,LT-7 Temporary Supply,,,3.19,,3.19,,3.19,,,3.19,,3.19,
6,,केरल / Kerala,,,2026-27,,,,,,,,,
7,,Category,,,KSEBL,,,,,,,,,
8,EHT- I,,,1.41,,,,,,,,,,
9,EHT- II,,,1.34,,,,,,,,,,
10,EHT-III and G(A),,,1.36,,,,,,,,,,
11,EHT-G (B),,,1.89,,,,,,,,,,
12,EHT-G (C),,,2.08,,,,,,,,,,
13,Railways & KMRL,,,1.40,,,,,,,,,,
14,Defence Installations,,,1.32,,,,,,,,,,

====================================================================================================
PAGE 54
====================================================================================================

TABLE 1

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,EHT Level,,,,,,,,,,...,,,,,,,,,,
1,HT & EHT Ferro Alloys Industrial,,,NIL,,,,,,,...,,,,,,,,,,
2,,ओिडशा / Odisha,,,2026-27,,,,,,...,,,,,,,,,,
3,,Category,,,TPCODL,,,TPNODL,,,...,,,,,,TPSODL,,,TPWODL,
4,EHT,,,,1.52,,,1.43,,,...,,,,,,1.18,,,2.50,
5,HT,,,,0.56,,,0.07,,,...,,,,,,0.17,,,1.06,
6,LT,,,,1.13,,,0.34,,,...,,,,,,0.24,,,1.40,
7,,पुडुचेरी / Puducherry,,,2026-27,,,,,,...,,,,,,,,,,
8,,Category,,,Puducherry Electricity Department (PED),,,,,,...,,,,,,,,,,
9,LT Level,,,NIL,,,,,,,...,,,,,,,,,,
10,HT Level,,,1.41,,,,,,,...,,,,,,,,,,
11,EHT Level,,,1.32,,,,,,,...,,,,,,,,,,
12,,पंजाब / Punjab,,,2026-27,,,,,,...,,,,,,,,,,
13,,Category,,,PSPCL,,,,,,...,,,,,,,,,,
14,Large Supply,,,0.86,,,,,,,...,,,,,,,,,,

====================================================================================================
PAGE 55
====================================================================================================

TABLE 1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,,HT Category 132kV,,,,,,,,,,,,,,,,,
1,HT-I Industry,,,1.62,,,,,,,,1.69,,,,,,,
2,HT-I(B)Ferro Alloys,,,-,,,,,,,,-,,,,,,,
3,HT-II Others (Commercial),,,2.34,,,,,,,,3.77,,,,,,,
4,"HT-III Airports, Bus & Rly Stations",,,1.71,,,,,,,,-,,,,,,,
5,HT-IV(A) Irrigation & Agriculture,,,1.60,,,,,,,,1.92,,,,,,,
6,HT-IV(B) CPWS,,,0.76,,,,,,,,0.58,,,,,,,
7,HT-V(A) Railway Traction,,,1.34,,,,,,,,1.01,,,,,,,
8,HT-V(B)HMR,,,0.53,,,,,,,,-,,,,,,,
9,HT-VI Townships & Residential Colonies,,,-,,,,,,,,1.74,,,,,,,
10,,ि(cid:361)पुरा / Tripura,,,2025-26,,,,,,,,,,,,,,
11,,Category,,,TSECL,,,,,,,,,,,,,,
12,,Commercial,,,,,,,,,,,,,,,,,
13,Semi-Commercial: All Units,,,1.90,,,,,,,,,,,,,,,
14,3-phase: All Units,,,1.93,,,,,,,,,,,,,,,

In [ ]:

import json
import pandas as pd



with open(
    "phase4_tables.json",
    "r",
    encoding="utf-8"
) as f:

    data = json.load(f)



def normalize_table(rows):

    if len(rows) == 0:
        return rows

    df = pd.DataFrame(rows)


    keep_cols = []

    for col in df.columns:

        values = (
            df[col]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        non_empty = (values != "").sum()

        if non_empty > 0:
            keep_cols.append(col)

    df = df[keep_cols]


    keep_rows = []

    for idx in df.index:

        vals = (
            df.loc[idx]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        if (vals != "").sum() > 0:
            keep_rows.append(idx)

    df = df.loc[keep_rows]

    return df.reset_index(
        drop=True
    ).values.tolist()


normalized = []

for page in data:

    page_out = {

        "page": page["page"],

        "tables": []
    }

    for table in page["tables"]:

        rows = table["rows"]

        clean_rows = normalize_table(
            rows
        )

        page_out["tables"].append({

            "table_id":
                table["table_id"],

            "rows":
                clean_rows,

            "n_rows":
                len(clean_rows),

            "n_cols":
                max(
                    [len(r) for r in clean_rows],
                    default=0
                )
        })

    normalized.append(page_out)


with open(
    "phase4_normalized.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        normalized,
        f,
        ensure_ascii=False,
        indent=2
    )

print("Saved phase4_normalized.json")

Saved phase4_normalized.json

In [ ]:
import json
import pandas as pd

with open(
    "phase4_normalized.json",
    "r",
    encoding="utf-8"
) as f:

    data = json.load(f)

for page in data:

    print("\n")
    print("="*80)
    print("PAGE", page["page"])
    print("="*80)

    for table in page["tables"]:

        print(
            "\nTABLE",
            table["table_id"],
            f"({table['n_rows']} x {table['n_cols']})"
        )

        display(
            pd.DataFrame(
                table["rows"]
            ).head(20)
        )

================================================================================
PAGE 50
================================================================================

TABLE 1 (25 x 8)

,0,1,2,3,4,5,6,7
0,,आं(cid:364) (cid:366)देश / Andhra Pradesh,,2026-27,,,,
1,,Category,,APSPDCL,,APEPDCL,,APCPDCL
2,,HT Category at 11 kV,,,,,,
3,"HT I(B) Townships, Colonies, Gated\nCommunitie...",,0.97,,0.89,,1.12,
4,HT II (A) Commercial& Others,,2.09,,2.20,,2.32,
5,HT II (A) Function Halls/ Auditoriums,,1.99,,1.99,,1.99,
6,HT II (B) Start-up power,,1.99,,1.99,,-,
7,HT III(A) Industry,,1.89,,1.71,,1.85,
8,HT III(B) Seasonal Industries (Off Season),,2.38,,1.76,,1.74,
9,HT III (C ) Energy Intensive Industries,,1.58,,-,,1.75,
10,HT IV (A) Utilities (Composite Protected Water...,,1.86,,1.91,,1.80,
11,HT IV (B) General Purpose,,2.28,,2.25,,2.13,
12,HT V (E ) Government/ Private Lift Irrigation,,-,,0.56,,0.57,
13,,HT Category at 33 kV,,,,,,
14,"HT I(B) Townships, Colonies, Gated\nCommunitie...",,1.52,,1.47,,1.50,
15,HT II(A) Commercial & Others,,2.28,,2.00,,1.84,
16,HT II(B) Start up power,,1.99,,1.99,,1.99,
17,HT III(A) Industry,,1.54,,1.48,,1.55,
18,HT III(B) Seasonal Industries (Off Season),,2.17,,1.53,,1.59,
19,HT III(C ) Energy Intensive Industries,,0.36,,0.24,,-,

================================================================================
PAGE 51
================================================================================

TABLE 1 (57 x 10)

,0,1,2,3,4,5,6,7,8,9
0,HT II(B) Start Up Power,,1.99,,1.99,,,,1.99,
1,HT III(A) Industry,,1.37,,1.44,,,,1.40,
2,HT III(C ) Energy Intensive Industry,,0.31,,0.51,,,,-,
3,HT IV(D) Railway Traction,,1.63,,1.59,,,,1.56,
4,HT V (E ),,1.43,,-,,,,1.43,
5,,220 kV,,,,,,,,
6,HT II(A) Commercial & Others,,-,,1.66,,,,-,
7,HT II(B) Start up Power,,1.99,,1.99,,,,-,
8,HT III(A) Industry,,1.57,,1.37,,,,1.96,
9,HT III (C ) Energy Intensive Industries,,-,,1.57,,,,-,
10,HT IV(D) Railway Traction,,1.66,,-,,,,-,
11,HT V (E ) Government/ Private Lift Irrigation,,1.43,,1.43,,,,-,
12,,असम / Assam,,2026-27,,,,,,
13,,Category,,APDCL,,,,,,
14,HT Domestic and Commercial 30 kW & above,,1.81,,,,,,,
15,Public Water Works,,1.81,,,,,,,
16,Bulk Supply Govt. Edu Inst and others,,1.81,,,,,,,
17,HT Small Industries up to 50 kW,,1.81,,,,,,,
18,HT Industries-I 50 kW to 150 kW,,1.81,,,,,,,
19,HT Industries-II above 150 kW,,1.81,,,,,,,

================================================================================
PAGE 52
================================================================================

TABLE 1 (58 x 13)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,गोवा / Goa,,,2026-27,,,,,,,,,
1,,Category,,"Electricity Department, Goa (EDG)",,,,,,,,,
2,Low Tension (LT) Level,,NIL,,,,,,,,,,
3,High Tension (HT)/ EHT Level,,1.13,,,,,,,,,,
4,Extra High Tension (EHT) Level,,0.68,,,,,,,,,,
5,गुजरात / Gujarat,,2026-27,,,,,,,,,,
6,,Category,,DGVCL,,PGVCL,,MGVCL,,,UGVCL,,
7,HT Category,,1.33,,1.33,,1.33,,,1.33,,,
8,ह(cid:303)रयाणा / Haryana,,,2026-27,,,,,,,,,
9,,Category,,UHBVNL,,,,,DHBVNL,,,,
10,HT Supply,,,1.45,,,,,1.45,,,,
11,Bulk Supply (other than DS),,,-,,,,,-,,,,
12,LT Supply,,,1.18,,,,,1.18,,,,
13,,िहमाचल (cid:366)देश / Himachal Pradesh,,2026-27,,,,,,,,,
14,Category,,HPSEBL,,,,,,,,,,
15,,,,Non-Peak hours,,,,,Peak Hours,,,,
16,Large Industrial Supply EHT Consumers,,,,,,,,,,,,
17,a) 66kV and above,,,0.66,,,,,0.70,,,,
18,b) HT1 (>100 KVA and up to 1 MVA),,,0.55,,,,,0.58,,,,
19,c) HT2 (>100 KVA and up to 1 MVA),,,0.59,,,,,0.62,,,,

================================================================================
PAGE 53
================================================================================

TABLE 1 (56 x 10)

,0,1,2,3,4,5,6,7,8,9
0,LT-3b,,3.05,,3.05,3.05,,3.05,,3.05
1,LT-4a,,0.49,,0.49,0.49,,0.49,,0.49
2,LT-4b,,1.07,,1.07,1.07,,1.07,,1.07
3,LT-4c,,1.85,,1.85,1.85,,1.85,,1.85
4,LT-5 Industrial,,1.16,,1.16,1.16,,1.16,,1.16
5,LT-7 Temporary Supply,,3.19,,3.19,3.19,,3.19,,3.19
6,,केरल / Kerala,,2026-27,,,,,,
7,,Category,,KSEBL,,,,,,
8,EHT- I,,1.41,,,,,,,
9,EHT- II,,1.34,,,,,,,
10,EHT-III and G(A),,1.36,,,,,,,
11,EHT-G (B),,1.89,,,,,,,
12,EHT-G (C),,2.08,,,,,,,
13,Railways & KMRL,,1.40,,,,,,,
14,Defence Installations,,1.32,,,,,,,
15,HT I(A) – Industry,,1.58,,,,,,,
16,HT I(B) – Industry,,1.71,,,,,,,
17,HT II – A,,1.65,,,,,,,
18,HT II – B,,1.92,,,,,,,
19,HT III – A,,1.25,,,,,,,

================================================================================
PAGE 54
================================================================================

TABLE 1 (54 x 12)

,0,1,2,3,4,5,6,7,8,9,10,11
0,EHT Level,,,,,,,,,,,
1,HT & EHT Ferro Alloys Industrial,,NIL,,,,,,,,,
2,,ओिडशा / Odisha,,2026-27,,,,,,,,
3,,Category,,TPCODL,TPNODL,,,,,,TPSODL,TPWODL
4,EHT,,,1.52,1.43,,,,,,1.18,2.50
5,HT,,,0.56,0.07,,,,,,0.17,1.06
6,LT,,,1.13,0.34,,,,,,0.24,1.40
7,,पुडुचेरी / Puducherry,,2026-27,,,,,,,,
8,,Category,,Puducherry Electricity Department (PED),,,,,,,,
9,LT Level,,NIL,,,,,,,,,
10,HT Level,,1.41,,,,,,,,,
11,EHT Level,,1.32,,,,,,,,,
12,,पंजाब / Punjab,,2026-27,,,,,,,,
13,,Category,,PSPCL,,,,,,,,
14,Large Supply,,0.86,,,,,,,,,
15,Non-Residential Supply,,1.22,,,,,,,,,
16,Bulk Supply,,1.22,,,,,,,,,
17,,राज(cid:830) थान / Rajasthan,,2026-27,,,,,,,,
18,,Category,,AVVNL,,,JdVVNL,,,,JVVNL,
19,,"Non- Domestic service, Mixed Load/ Bulk Supply...",,,,,,,,,,

================================================================================
PAGE 55
================================================================================

TABLE 1 (58 x 13)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,,HT Category 132kV,,,,,,,,,,,
1,HT-I Industry,,1.62,,,,,,1.69,,,,
2,HT-I(B)Ferro Alloys,,-,,,,,,-,,,,
3,HT-II Others (Commercial),,2.34,,,,,,3.77,,,,
4,"HT-III Airports, Bus & Rly Stations",,1.71,,,,,,-,,,,
5,HT-IV(A) Irrigation & Agriculture,,1.60,,,,,,1.92,,,,
6,HT-IV(B) CPWS,,0.76,,,,,,0.58,,,,
7,HT-V(A) Railway Traction,,1.34,,,,,,1.01,,,,
8,HT-V(B)HMR,,0.53,,,,,,-,,,,
9,HT-VI Townships & Residential Colonies,,-,,,,,,1.74,,,,
10,,ि(cid:361)पुरा / Tripura,,2025-26,,,,,,,,,
11,,Category,,TSECL,,,,,,,,,
12,,Commercial,,,,,,,,,,,
13,Semi-Commercial: All Units,,1.90,,,,,,,,,,
14,3-phase: All Units,,1.93,,,,,,,,,,
15,3-phase group,,1.91,,,,,,,,,,
16,,Irrigation,,,,,,,,,,,
17,Above 5 H.P.: All units,,0.43,,,,,,,,,,
18,,Industrial,,,,,,,,,,,
19,Up to 5 HP (E-R/5),,0.72,,,,,,,,,,

In [ ]:


import json
import re


with open(
    "phase4_normalized.json",
    "r",
    encoding="utf-8"
) as f:

    data = json.load(f)


YEAR_RE = re.compile(
    r"20\d{2}\-\d{2}"
)


def find_state_name(row):

    text = " ".join(
        [str(x) for x in row]
    )

    text = text.strip()

    if not YEAR_RE.search(text):
        return None

    parts = text.split("/")

    if len(parts) > 1:

        state = parts[-1].strip()

        state = YEAR_RE.sub(
            "",
            state
        ).strip()

        return state

    return None


blocks = []

for page in data:

    for table in page["tables"]:

        rows = table["rows"]

        current = None

        for row in rows:

            state = find_state_name(row)

            if state:

                if current:
                    blocks.append(current)

                current = {

                    "page":
                        page["page"],

                    "state":
                        state,

                    "rows": []
                }

                continue

            if current:
                current["rows"].append(row)

        if current:
            blocks.append(current)


with open(
    "state_blocks.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        blocks,
        f,
        ensure_ascii=False,
        indent=2
    )

print(
    "Detected blocks:",
    len(blocks)
)



for b in blocks[:10]:

    print()
    print("="*60)

    print(
        "STATE:",
        b["state"]
    )

    print(
        "PAGE:",
        b["page"]
    )

    print(
        "ROWS:",
        len(b["rows"])
    )

    for r in b["rows"][:5]:
        print(r)

Detected blocks: 28

============================================================
STATE: Andhra Pradesh
PAGE: 50
ROWS: 24
['', 'Category', '', 'APSPDCL', '', 'APEPDCL', '', 'APCPDCL']
['', 'HT Category at 11 kV', '', '', '', '', '', '']
['HT I(B) Townships, Colonies, Gated\nCommunities and Villas', '', '0.97', '', '0.89', '', '1.12', '']
['HT II (A) Commercial& Others', '', '2.09', '', '2.20', '', '2.32', '']
['HT II (A) Function Halls/ Auditoriums', '', '1.99', '', '1.99', '', '1.99', '']

============================================================
STATE: Assam
PAGE: 51
ROWS: 11
['', 'Category', '', 'APDCL', '', '', '', '', '', '']
['HT Domestic and Commercial 30 kW & above', '', '1.81', '', '', '', '', '', '', '']
['Public Water Works', '', '1.81', '', '', '', '', '', '', '']
['Bulk Supply Govt. Edu Inst and others', '', '1.81', '', '', '', '', '', '', '']
['HT Small Industries up to 50 kW', '', '1.81', '', '', '', '', '', '', '']

============================================================
STATE: Bihar
PAGE: 51
ROWS: 3
['', 'Category', '', 'NBPDCL', '', '', '', 'SBPDCL', '', '']
['', 'HT Category', '', '', '', '', '', '', '', '']
['', 'For 11 kV, 33 kV,132 kV, 220 & 400 kV', '', '1.77', '', '', '', '1.68', '', '']

============================================================
STATE: Chandigarh
PAGE: 51
ROWS: 4
['', 'Category', '', 'Chandigarh Power Distribution Limited (CPDL)', '', '', '', '', '', '']
['LT Level', '', 'NIL', '', '', '', '', '', '', '']
['High Tension (HT)/ EHT', '', '0.61', '', '', '', '', '', '', '']
['(EHxTtr)a/E HHigThE xTteran sHioignh ( ETHenTs)i oLne vel', '', '0.82', '', '', '', '', '', '', '']

============================================================
STATE: Chhattisgarh
PAGE: 51
ROWS: 12
['', 'Category', '', 'CSPDCL', '', '', '', '', '', '']
['', '', 'For Non-RE Transactions', '', '', '', 'For RE Transactions', '', '', '']
['220 kV & above', '', '1.33', '', '', '', '1.33', '', '', '']
['132 kV', '', '0.94', '', '', '', '0.94', '', '', '']
['33 kV & 11 kV', '', '1.40', '', '', '', '1.40', '', '', '']

============================================================
STATE: Delhi
PAGE: 51
ROWS: 10
['', 'Category', '', 'BRPL', '', 'BYPL', '', '', '', 'TPDDL']
['Industrial', '', '', '', '', '', '', '', '', '']
['At LT level,11 kV/ 33kV/ 66kV & above 66kV', '', '1.90', '', '1.88', '', '', '', '1.87', '']
['', 'level\nNon-Domestic', '', '', '', '', '', '', '', '']
['At LT level,11 kV/ 33kV/ 66kV & above 66kV', '', '2.24', '', '2.27', '', '', '', '2.18', '']

============================================================
STATE: Goa
PAGE: 52
ROWS: 4
['', 'Category', '', 'Electricity Department, Goa (EDG)', '', '', '', '', '', '', '', '', '']
['Low Tension (LT) Level', '', 'NIL', '', '', '', '', '', '', '', '', '', '']
['High Tension (HT)/ EHT Level', '', '1.13', '', '', '', '', '', '', '', '', '', '']
['Extra High Tension (EHT) Level', '', '0.68', '', '', '', '', '', '', '', '', '', '']

============================================================
STATE: Gujarat
PAGE: 52
ROWS: 2
['', 'Category', '', 'DGVCL', '', 'PGVCL', '', 'MGVCL', '', '', 'UGVCL', '', '']
['HT Category', '', '1.33', '', '1.33', '', '1.33', '', '', '1.33', '', '', '']

============================================================
STATE: Haryana
PAGE: 52
ROWS: 4
['', 'Category', '', 'UHBVNL', '', '', '', '', 'DHBVNL', '', '', '', '']
['HT Supply', '', '', '1.45', '', '', '', '', '1.45', '', '', '', '']
['Bulk Supply (other than DS)', '', '', '-', '', '', '', '', '-', '', '', '', '']
['LT Supply', '', '', '1.18', '', '', '', '', '1.18', '', '', '', '']

============================================================
STATE: Himachal Pradesh
PAGE: 52
ROWS: 12
['Category', '', 'HPSEBL', '', '', '', '', '', '', '', '', '', '']
['', '', '', 'Non-Peak hours', '', '', '', '', 'Peak Hours', '', '', '', '']
['Large Industrial Supply EHT Consumers', '', '', '', '', '', '', '', '', '', '', '', '']
['a) 66kV and above', '', '', '0.66', '', '', '', '', '0.70', '', '', '', '']
['b) HT1 (>100 KVA and up to 1 MVA)', '', '', '0.55', '', '', '', '', '0.58', '', '', '', '']

In [ ]:


import json
import re



with open(
    "phase4_normalized.json",
    "r",
    encoding="utf-8"
) as f:
    data = json.load(f)


YEAR_RE = re.compile(
    r"20\d{2}-\d{2}"
)

def detect_state(row):

    text = " ".join(
        [str(x) for x in row]
    )

    if not YEAR_RE.search(text):
        return None

    if "/" not in text:
        return None

    state = text.split("/")[-1]

    state = YEAR_RE.sub(
        "",
        state
    )

    return state.strip()


stream = []

for page in data:

    page_num = page["page"]

    for table in page["tables"]:

        for row in table["rows"]:

            stream.append({

                "page": page_num,

                "row": row
            })



blocks = []

current = None

for item in stream:

    row = item["row"]

    state = detect_state(row)

    if state:

        if current:

            blocks.append(
                current
            )

        current = {

            "state": state,

            "start_page":
                item["page"],

            "rows": []
        }

        continue

    if current:

        current["rows"].append(
            row
        )

# final block

if current:

    blocks.append(
        current
    )


with open(
    "state_blocks_v2.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        blocks,
        f,
        ensure_ascii=False,
        indent=2
    )

print(
    "Blocks:",
    len(blocks)
)

for b in blocks[:10]:

    print(
        b["state"],
        "rows:",
        len(b["rows"])
    )

Blocks: 28
Andhra Pradesh rows: 36
Assam rows: 11
Bihar rows: 3
Chandigarh rows: 4
Chhattisgarh rows: 12
Delhi rows: 10
Goa rows: 4
Gujarat rows: 2
Haryana rows: 4
Himachal Pradesh rows: 12

In [ ]:

def parse_simple_matrix_state(block):

    rows = []

    for r in block["rows"]:

        c = compress_row(r)

        if c:
            rows.append(c)

    if len(rows) < 2:

        return {

            "state":
                block["state"],

            "start_page":
                block["start_page"],

            "parser_type":
                "simple_matrix",

            "columns": [],

            "rows": []
        }

    header = rows[0]

    columns = header[1:]

    parsed_rows = []

    for row in rows[1:]:

        entry = {

            "category":
                row[0]
        }

        for col, val in zip(
            columns,
            row[1:]
        ):

            entry[col] = val

        parsed_rows.append(
            entry
        )

    return {

        "state":
            block["state"],

        "start_page":
            block["start_page"],

        "parser_type":
            "simple_matrix",

        "columns":
            columns,

        "rows":
            parsed_rows
    }

In [ ]:
def detect_parser_type(block):

    rows = []

    for r in block["rows"]:

        c = compress_row(r)

        if c:
            rows.append(c)

    if not rows:

        return "unknown"


    header = rows[0]

    if (
        len(header) > 1
        and header[0].lower() == "category"
    ):

        # sectioned matrix

        for r in rows[1:]:

            if len(r) == 1:

                return "matrix"

        # no sections

        return "simple_matrix"


    return "key_value"

In [ ]:
import json

with open(
    "state_blocks_v2.json",
    "r",
    encoding="utf-8"
) as f:

    blocks = json.load(f)

ap = next(
    b for b in blocks
    if b["state"] == "Andhra Pradesh"
)

print(
    "AP rows:",
    len(ap["rows"])
)

for r in ap["rows"][-20:]:

    print(r)

AP rows: 36
['HT III(A) Industry', '', '1.54', '', '1.48', '', '1.55', '']
['HT III(B) Seasonal Industries (Off Season)', '', '2.17', '', '1.53', '', '1.59', '']
['HT III(C ) Energy Intensive Industries', '', '0.36', '', '0.24', '', '-', '']
['HT IV(A) Utilities (Composite Protected Water\nSupply Schemes)', '', '1.76', '', '2.13', '', '-', '']
['HT IV(B) General Purpose', '', '1.90', '', '2.04', '', '1.74', '']
['HT V(E) Government/ Private Lift Irrigation', '', '1.25', '', '1.27', '', '1.25', '']
['', 'HT Category at 132 kV', '', '', '', '', '', '']
['HT II(A) Commercial & Others', '', '1.69', '', '1.99', '', '-', '']
['HT II(B) Start Up Power', '', '1.99', '', '1.99', '', '', '', '1.99', '']
['HT III(A) Industry', '', '1.37', '', '1.44', '', '', '', '1.40', '']
['HT III(C ) Energy Intensive Industry', '', '0.31', '', '0.51', '', '', '', '-', '']
['HT IV(D) Railway Traction', '', '1.63', '', '1.59', '', '', '', '1.56', '']
['HT V (E )', '', '1.43', '', '-', '', '', '', '1.43', '']
['', '220 kV', '', '', '', '', '', '', '', '']
['HT II(A) Commercial & Others', '', '-', '', '1.66', '', '', '', '-', '']
['HT II(B) Start up Power', '', '1.99', '', '1.99', '', '', '', '-', '']
['HT III(A) Industry', '', '1.57', '', '1.37', '', '', '', '1.96', '']
['HT III (C ) Energy Intensive Industries', '', '-', '', '1.57', '', '', '', '-', '']
['HT IV(D) Railway Traction', '', '1.66', '', '-', '', '', '', '-', '']
['HT V (E ) Government/ Private Lift Irrigation', '', '1.43', '', '1.43', '', '', '', '-', '']

In [ ]:
# # ==========================================================
# # PHASE 4.4
# # BUILD STATE CATALOG
# # ==========================================================

# import json
# import pandas as pd

# with open(
#     "state_blocks.json",
#     "r",
#     encoding="utf-8"
# ) as f:
#     blocks = json.load(f)

# catalog = []

# for i, block in enumerate(blocks):

#     text_parts = []

#     for row in block["rows"]:
#         text_parts.extend(
#             [str(x) for x in row]
#         )

#     catalog.append({

#         "block_id": i,

#         "state": block["state"],

#         "page": block["page"],

#         "row_count": len(
#             block["rows"]
#         ),

#         "search_text":
#             " ".join(text_parts)
#     })

# catalog_df = pd.DataFrame(
#     catalog
# )

# catalog_df.to_csv(
#     "state_catalog.csv",
#     index=False
# )

# print(
#     "Total blocks:",
#     len(catalog_df)
# )

# display(
#     catalog_df[
#         [
#             "block_id",
#             "state",
#             "page",
#             "row_count"
#         ]
#     ]
# )

KeyError: 'page'

In [ ]:


import json
import pandas as pd



with open(
    "state_blocks_v2.json",
    "r",
    encoding="utf-8"
) as f:

    blocks = json.load(f)



catalog = []

for block_id, block in enumerate(blocks):

    text_parts = []

    for row in block["rows"]:

        text_parts.extend(
            [str(x) for x in row]
        )

    catalog.append({

        "block_id":
            block_id,

        "state":
            block["state"],

        "start_page":
            block["start_page"],

        "row_count":
            len(block["rows"]),

        "search_text":
            " ".join(text_parts)
    })

catalog_df = pd.DataFrame(
    catalog
)



catalog_df.to_csv(
    "state_catalog_v2.csv",
    index=False
)



print("="*70)
print("STATE CATALOG")
print("="*70)

print(
    "Total States:",
    len(catalog_df)
)

display(
    catalog_df[
        [
            "block_id",
            "state",
            "start_page",
            "row_count"
        ]
    ]
)

======================================================================
STATE CATALOG
======================================================================
Total States: 28

    block_id             state  start_page  row_count
0          0    Andhra Pradesh          50         36
1          1             Assam          51         11
2          2             Bihar          51          3
3          3        Chandigarh          51          4
4          4      Chhattisgarh          51         12
5          5             Delhi          51         10
6          6               Goa          52          4
7          7           Gujarat          52          2
8          8           Haryana          52          4
9          9  Himachal Pradesh          52         12
10        10   Jammu & Kashmir          52          2
11        11         Jharkhand          52          2
12        12         Karnataka          52         31
13        13            Kerala          53         18
14        14    Madhya Pradesh          53         16
15        15       Maharashtra          53         10
16        16         Meghalaya          53          4
17        17            Odisha          54          4
18        18        Puducherry          54          4
19        19            Punjab          54          4
20        20         Rajasthan          54          3
21        21            Sikkim          54          2
22        22        Tamil Nadu          54          6
23        23         Telangana          54         32
24        24           Tripura          55         21
25        25     Uttar Pradesh          55         12
26        26       Uttarakhand          55          4
27        27       West Bengal          55          7

In [ ]:


import json
import pandas as pd

catalog = pd.read_csv(
    "state_catalog.csv"
)

with open(
    "state_blocks_v2.json",
    "r",
    encoding="utf-8"
) as f:
    blocks = json.load(f)

def retrieve_state(
    state_name
):

    hits = catalog[
        catalog["state"]
        .str.contains(
            state_name,
            case=False,
            na=False
        )
    ]

    if len(hits) == 0:

        return None

    block_id = int(
        hits.iloc[0]["block_id"]
    )

    return blocks[
        block_id
    ]



for state in [

    "Andhra Pradesh",
    "Goa",
    "Haryana",
    "Delhi"

]:

    result = retrieve_state(
        state
    )

    print()
    print("="*60)
    print(state)
    print("="*60)

    print(
        "Rows:",
        len(result["rows"])
    )

    for r in result["rows"][:10]:
        print(r)

============================================================
Andhra Pradesh
============================================================
Rows: 36
['', 'Category', '', 'APSPDCL', '', 'APEPDCL', '', 'APCPDCL']
['', 'HT Category at 11 kV', '', '', '', '', '', '']
['HT I(B) Townships, Colonies, Gated\nCommunities and Villas', '', '0.97', '', '0.89', '', '1.12', '']
['HT II (A) Commercial& Others', '', '2.09', '', '2.20', '', '2.32', '']
['HT II (A) Function Halls/ Auditoriums', '', '1.99', '', '1.99', '', '1.99', '']
['HT II (B) Start-up power', '', '1.99', '', '1.99', '', '-', '']
['HT III(A) Industry', '', '1.89', '', '1.71', '', '1.85', '']
['HT III(B) Seasonal Industries (Off Season)', '', '2.38', '', '1.76', '', '1.74', '']
['HT III (C ) Energy Intensive Industries', '', '1.58', '', '-', '', '1.75', '']
['HT IV (A) Utilities (Composite Protected Water\nSupply Schemes)', '', '1.86', '', '1.91', '', '1.80', '']

============================================================
Goa
============================================================
Rows: 4
['', 'Category', '', 'Electricity Department, Goa (EDG)', '', '', '', '', '', '', '', '', '']
['Low Tension (LT) Level', '', 'NIL', '', '', '', '', '', '', '', '', '', '']
['High Tension (HT)/ EHT Level', '', '1.13', '', '', '', '', '', '', '', '', '', '']
['Extra High Tension (EHT) Level', '', '0.68', '', '', '', '', '', '', '', '', '', '']

============================================================
Haryana
============================================================
Rows: 4
['', 'Category', '', 'UHBVNL', '', '', '', '', 'DHBVNL', '', '', '', '']
['HT Supply', '', '', '1.45', '', '', '', '', '1.45', '', '', '', '']
['Bulk Supply (other than DS)', '', '', '-', '', '', '', '', '-', '', '', '', '']
['LT Supply', '', '', '1.18', '', '', '', '', '1.18', '', '', '', '']

============================================================
Delhi
============================================================
Rows: 10
['', 'Category', '', 'BRPL', '', 'BYPL', '', '', '', 'TPDDL']
['Industrial', '', '', '', '', '', '', '', '', '']
['At LT level,11 kV/ 33kV/ 66kV & above 66kV', '', '1.90', '', '1.88', '', '', '', '1.87', '']
['', 'level\nNon-Domestic', '', '', '', '', '', '', '', '']
['At LT level,11 kV/ 33kV/ 66kV & above 66kV', '', '2.24', '', '2.27', '', '', '', '2.18', '']
['', 'DMRC & DJB', '', '', '', '', '', '', '', '']
['Above 66kV level', '', '1.47', '', '1.53', '', '', '', '0.79', '']
['At 33/ 66kV level', '', '0.54', '', '1.29', '', '', '', '0.75', '']
['At 11 kV level', '', '0.47', '', '1.23', '', '', '', '0.64', '']
['At LT level', '', '0.03', '', '0.8', '', '', '', '0.26', '']

In [ ]:


import pandas as pd

catalog = pd.read_csv(
    "state_catalog_v2.csv"
)

ALL_STATES = sorted(
    catalog["state"].unique()
)

def detect_state(query):

    q = query.lower()

    for state in ALL_STATES:

        if state.lower() in q:

            return state

    return None


tests = [

    "Extract Goa Open Access Charges",

    "Show Haryana Open Access Charges",

    "Get Andhra Pradesh Charges",

    "Delhi Open Access Charges",

    "What is the OA charge in Gujarat"
]

for t in tests:

    print()
    print("QUERY :", t)

    print(
        "STATE :",
        detect_state(t)
    )

QUERY : Extract Goa Open Access Charges
STATE : Goa

QUERY : Show Haryana Open Access Charges
STATE : Haryana

QUERY : Get Andhra Pradesh Charges
STATE : Andhra Pradesh

QUERY : Delhi Open Access Charges
STATE : Delhi

QUERY : What is the OA charge in Gujarat
STATE : Gujarat

In [ ]:


import json
import pandas as pd

catalog = pd.read_csv(
    "state_catalog_v2.csv"
)

with open(
    "state_blocks_v2.json",
    "r",
    encoding="utf-8"
) as f:

    blocks = json.load(f)

def detect_state(query):

    q = query.lower()

    for state in catalog["state"]:

        if state.lower() in q:

            return state

    return None

def retrieve_block(query):

    state = detect_state(query)

    if state is None:

        return None

    hit = catalog[
        catalog["state"] == state
    ].iloc[0]

    return blocks[
        int(hit["block_id"])
    ]



query = (
    "Extract Andhra Pradesh Open Access Charges"
)

result = retrieve_block(
    query
)

print(
    json.dumps(
        result,
        indent=2,
        ensure_ascii=False
    )
)

{
  "state": "Andhra Pradesh",
  "start_page": 50,
  "rows": [
    [
      "",
      "Category",
      "",
      "APSPDCL",
      "",
      "APEPDCL",
      "",
      "APCPDCL"
    ],
    [
      "",
      "HT Category at 11 kV",
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    [
      "HT I(B) Townships, Colonies, Gated\nCommunities and Villas",
      "",
      "0.97",
      "",
      "0.89",
      "",
      "1.12",
      ""
    ],
    [
      "HT II (A) Commercial& Others",
      "",
      "2.09",
      "",
      "2.20",
      "",
      "2.32",
      ""
    ],
    [
      "HT II (A) Function Halls/ Auditoriums",
      "",
      "1.99",
      "",
      "1.99",
      "",
      "1.99",
      ""
    ],
    [
      "HT II (B) Start-up power",
      "",
      "1.99",
      "",
      "1.99",
      "",
      "-",
      ""
    ],
    [
      "HT III(A) Industry",
      "",
      "1.89",
      "",
      "1.71",
      "",
      "1.85",
      ""
    ],
    [
      "HT III(B) Seasonal Industries (Off Season)",
      "",
      "2.38",
      "",
      "1.76",
      "",
      "1.74",
      ""
    ],
    [
      "HT III (C ) Energy Intensive Industries",
      "",
      "1.58",
      "",
      "-",
      "",
      "1.75",
      ""
    ],
    [
      "HT IV (A) Utilities (Composite Protected Water\nSupply Schemes)",
      "",
      "1.86",
      "",
      "1.91",
      "",
      "1.80",
      ""
    ],
    [
      "HT IV (B) General Purpose",
      "",
      "2.28",
      "",
      "2.25",
      "",
      "2.13",
      ""
    ],
    [
      "HT V (E ) Government/ Private Lift Irrigation",
      "",
      "-",
      "",
      "0.56",
      "",
      "0.57",
      ""
    ],
    [
      "",
      "HT Category at 33 kV",
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    [
      "HT I(B) Townships, Colonies, Gated\nCommunities, Villas",
      "",
      "1.52",
      "",
      "1.47",
      "",
      "1.50",
      ""
    ],
    [
      "HT II(A) Commercial & Others",
      "",
      "2.28",
      "",
      "2.00",
      "",
      "1.84",
      ""
    ],
    [
      "HT II(B) Start up power",
      "",
      "1.99",
      "",
      "1.99",
      "",
      "1.99",
      ""
    ],
    [
      "HT III(A) Industry",
      "",
      "1.54",
      "",
      "1.48",
      "",
      "1.55",
      ""
    ],
    [
      "HT III(B) Seasonal Industries (Off Season)",
      "",
      "2.17",
      "",
      "1.53",
      "",
      "1.59",
      ""
    ],
    [
      "HT III(C ) Energy Intensive Industries",
      "",
      "0.36",
      "",
      "0.24",
      "",
      "-",
      ""
    ],
    [
      "HT IV(A) Utilities (Composite Protected Water\nSupply Schemes)",
      "",
      "1.76",
      "",
      "2.13",
      "",
      "-",
      ""
    ],
    [
      "HT IV(B) General Purpose",
      "",
      "1.90",
      "",
      "2.04",
      "",
      "1.74",
      ""
    ],
    [
      "HT V(E) Government/ Private Lift Irrigation",
      "",
      "1.25",
      "",
      "1.27",
      "",
      "1.25",
      ""
    ],
    [
      "",
      "HT Category at 132 kV",
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    [
      "HT II(A) Commercial & Others",
      "",
      "1.69",
      "",
      "1.99",
      "",
      "-",
      ""
    ],
    [
      "HT II(B) Start Up Power",
      "",
      "1.99",
      "",
      "1.99",
      "",
      "",
      "",
      "1.99",
      ""
    ],
    [
      "HT III(A) Industry",
      "",
      "1.37",
      "",
      "1.44",
      "",
      "",
      "",
      "1.40",
      ""
    ],
    [
      "HT III(C ) Energy Intensive Industry",
      "",
      "0.31",
      "",
      "0.51",
      "",
      "",
      "",
      "-",
      ""
    ],
    [
      "HT IV(D) Railway Traction",
      "",
      "1.63",
      "",
      "1.59",
      "",
      "",
      "",
      "1.56",
      ""
    ],
    [
      "HT V (E )",
      "",
      "1.43",
      "",
      "-",
      "",
      "",
      "",
      "1.43",
      ""
    ],
    [
      "",
      "220 kV",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    [
      "HT II(A) Commercial & Others",
      "",
      "-",
      "",
      "1.66",
      "",
      "",
      "",
      "-",
      ""
    ],
    [
      "HT II(B) Start up Power",
      "",
      "1.99",
      "",
      "1.99",
      "",
      "",
      "",
      "-",
      ""
    ],
    [
      "HT III(A) Industry",
      "",
      "1.57",
      "",
      "1.37",
      "",
      "",
      "",
      "1.96",
      ""
    ],
    [
      "HT III (C ) Energy Intensive Industries",
      "",
      "-",
      "",
      "1.57",
      "",
      "",
      "",
      "-",
      ""
    ],
    [
      "HT IV(D) Railway Traction",
      "",
      "1.66",
      "",
      "-",
      "",
      "",
      "",
      "-",
      ""
    ],
    [
      "HT V (E ) Government/ Private Lift Irrigation",
      "",
      "1.43",
      "",
      "1.43",
      "",
      "",
      "",
      "-",
      ""
    ]
  ]
}

In [ ]:


import json

with open(
    "state_blocks_v2.json",
    "r",
    encoding="utf-8"
) as f:
    blocks = json.load(f)



goa = None

for b in blocks:

    if b["state"] == "Goa":

        goa = b
        break


def compress_row(row):

    vals = []

    for x in row:

        x = str(x).strip()

        if x != "":
            vals.append(x)

    return vals



compressed = []

for row in goa["rows"]:

    r = compress_row(row)

    if len(r) > 0:
        compressed.append(r)

print(
    json.dumps(
        compressed,
        indent=2,
        ensure_ascii=False
    )
)

[
  [
    "Category",
    "Electricity Department, Goa (EDG)"
  ],
  [
    "Low Tension (LT) Level",
    "NIL"
  ],
  [
    "High Tension (HT)/ EHT Level",
    "1.13"
  ],
  [
    "Extra High Tension (EHT) Level",
    "0.68"
  ]
]

In [ ]:


import json

with open(
    "state_blocks_v2.json",
    "r",
    encoding="utf-8"
) as f:
    blocks = json.load(f)

STATE = "Haryana"

block = None

for b in blocks:
    if b["state"] == STATE:
        block = b
        break

def compress_row(row):

    return [
        str(x).strip()
        for x in row
        if str(x).strip() != ""
    ]

compressed = []

for row in block["rows"]:

    r = compress_row(row)

    if r:
        compressed.append(r)

print(
    json.dumps(
        compressed[:20],
        indent=2,
        ensure_ascii=False
    )
)

[
  [
    "Category",
    "UHBVNL",
    "DHBVNL"
  ],
  [
    "HT Supply",
    "1.45",
    "1.45"
  ],
  [
    "Bulk Supply (other than DS)",
    "-",
    "-"
  ],
  [
    "LT Supply",
    "1.18",
    "1.18"
  ]
]

In [ ]:


import json

with open(
    "state_blocks_v2.json",
    "r",
    encoding="utf-8"
) as f:
    blocks = json.load(f)



block = next(
    b for b in blocks
    if b["state"] == "Andhra Pradesh"
)


def compress_row(row):

    return [
        str(x).strip()
        for x in row
        if str(x).strip() != ""
    ]

rows = []

for r in block["rows"]:

    c = compress_row(r)

    if c:
        rows.append(c)



columns = None

sections = []

current_section = None

for row in rows:

    # header row

    if (
        len(row) > 1
        and row[0].lower() == "category"
    ):

        columns = row[1:]

        continue

    # section row

    if len(row) == 1:

        current_section = {

            "name": row[0],

            "columns": columns,

            "rows": []
        }

        sections.append(
            current_section
        )

        continue

    # data row

    if current_section:

        entry = {

            "category": row[0]
        }

        for col, val in zip(
            columns,
            row[1:]
        ):

            entry[col] = val

        current_section["rows"].append(
            entry
        )



result = {

    "state":
        "Andhra Pradesh",

    "sections":
        sections
}

print(
    json.dumps(
        result,
        indent=2,
        ensure_ascii=False
    )
)

{
  "state": "Andhra Pradesh",
  "sections": [
    {
      "name": "HT Category at 11 kV",
      "columns": [
        "APSPDCL",
        "APEPDCL",
        "APCPDCL"
      ],
      "rows": [
        {
          "category": "HT I(B) Townships, Colonies, Gated\nCommunities and Villas",
          "APSPDCL": "0.97",
          "APEPDCL": "0.89",
          "APCPDCL": "1.12"
        },
        {
          "category": "HT II (A) Commercial& Others",
          "APSPDCL": "2.09",
          "APEPDCL": "2.20",
          "APCPDCL": "2.32"
        },
        {
          "category": "HT II (A) Function Halls/ Auditoriums",
          "APSPDCL": "1.99",
          "APEPDCL": "1.99",
          "APCPDCL": "1.99"
        },
        {
          "category": "HT II (B) Start-up power",
          "APSPDCL": "1.99",
          "APEPDCL": "1.99",
          "APCPDCL": "-"
        },
        {
          "category": "HT III(A) Industry",
          "APSPDCL": "1.89",
          "APEPDCL": "1.71",
          "APCPDCL": "1.85"
        },
        {
          "category": "HT III(B) Seasonal Industries (Off Season)",
          "APSPDCL": "2.38",
          "APEPDCL": "1.76",
          "APCPDCL": "1.74"
        },
        {
          "category": "HT III (C ) Energy Intensive Industries",
          "APSPDCL": "1.58",
          "APEPDCL": "-",
          "APCPDCL": "1.75"
        },
        {
          "category": "HT IV (A) Utilities (Composite Protected Water\nSupply Schemes)",
          "APSPDCL": "1.86",
          "APEPDCL": "1.91",
          "APCPDCL": "1.80"
        },
        {
          "category": "HT IV (B) General Purpose",
          "APSPDCL": "2.28",
          "APEPDCL": "2.25",
          "APCPDCL": "2.13"
        },
        {
          "category": "HT V (E ) Government/ Private Lift Irrigation",
          "APSPDCL": "-",
          "APEPDCL": "0.56",
          "APCPDCL": "0.57"
        }
      ]
    },
    {
      "name": "HT Category at 33 kV",
      "columns": [
        "APSPDCL",
        "APEPDCL",
        "APCPDCL"
      ],
      "rows": [
        {
          "category": "HT I(B) Townships, Colonies, Gated\nCommunities, Villas",
          "APSPDCL": "1.52",
          "APEPDCL": "1.47",
          "APCPDCL": "1.50"
        },
        {
          "category": "HT II(A) Commercial & Others",
          "APSPDCL": "2.28",
          "APEPDCL": "2.00",
          "APCPDCL": "1.84"
        },
        {
          "category": "HT II(B) Start up power",
          "APSPDCL": "1.99",
          "APEPDCL": "1.99",
          "APCPDCL": "1.99"
        },
        {
          "category": "HT III(A) Industry",
          "APSPDCL": "1.54",
          "APEPDCL": "1.48",
          "APCPDCL": "1.55"
        },
        {
          "category": "HT III(B) Seasonal Industries (Off Season)",
          "APSPDCL": "2.17",
          "APEPDCL": "1.53",
          "APCPDCL": "1.59"
        },
        {
          "category": "HT III(C ) Energy Intensive Industries",
          "APSPDCL": "0.36",
          "APEPDCL": "0.24",
          "APCPDCL": "-"
        },
        {
          "category": "HT IV(A) Utilities (Composite Protected Water\nSupply Schemes)",
          "APSPDCL": "1.76",
          "APEPDCL": "2.13",
          "APCPDCL": "-"
        },
        {
          "category": "HT IV(B) General Purpose",
          "APSPDCL": "1.90",
          "APEPDCL": "2.04",
          "APCPDCL": "1.74"
        },
        {
          "category": "HT V(E) Government/ Private Lift Irrigation",
          "APSPDCL": "1.25",
          "APEPDCL": "1.27",
          "APCPDCL": "1.25"
        }
      ]
    },
    {
      "name": "HT Category at 132 kV",
      "columns": [
        "APSPDCL",
        "APEPDCL",
        "APCPDCL"
      ],
      "rows": [
        {
          "category": "HT II(A) Commercial & Others",
          "APSPDCL": "1.69",
          "APEPDCL": "1.99",
          "APCPDCL": "-"
        },
        {
          "category": "HT II(B) Start Up Power",
          "APSPDCL": "1.99",
          "APEPDCL": "1.99",
          "APCPDCL": "1.99"
        },
        {
          "category": "HT III(A) Industry",
          "APSPDCL": "1.37",
          "APEPDCL": "1.44",
          "APCPDCL": "1.40"
        },
        {
          "category": "HT III(C ) Energy Intensive Industry",
          "APSPDCL": "0.31",
          "APEPDCL": "0.51",
          "APCPDCL": "-"
        },
        {
          "category": "HT IV(D) Railway Traction",
          "APSPDCL": "1.63",
          "APEPDCL": "1.59",
          "APCPDCL": "1.56"
        },
        {
          "category": "HT V (E )",
          "APSPDCL": "1.43",
          "APEPDCL": "-",
          "APCPDCL": "1.43"
        }
      ]
    },
    {
      "name": "220 kV",
      "columns": [
        "APSPDCL",
        "APEPDCL",
        "APCPDCL"
      ],
      "rows": [
        {
          "category": "HT II(A) Commercial & Others",
          "APSPDCL": "-",
          "APEPDCL": "1.66",
          "APCPDCL": "-"
        },
        {
          "category": "HT II(B) Start up Power",
          "APSPDCL": "1.99",
          "APEPDCL": "1.99",
          "APCPDCL": "-"
        },
        {
          "category": "HT III(A) Industry",
          "APSPDCL": "1.57",
          "APEPDCL": "1.37",
          "APCPDCL": "1.96"
        },
        {
          "category": "HT III (C ) Energy Intensive Industries",
          "APSPDCL": "-",
          "APEPDCL": "1.57",
          "APCPDCL": "-"
        },
        {
          "category": "HT IV(D) Railway Traction",
          "APSPDCL": "1.66",
          "APEPDCL": "-",
          "APCPDCL": "-"
        },
        {
          "category": "HT V (E ) Government/ Private Lift Irrigation",
          "APSPDCL": "1.43",
          "APEPDCL": "1.43",
          "APCPDCL": "-"
        }
      ]
    }
  ]
}

In [ ]:


import json



with open(
    "state_blocks_v2.json",
    "r",
    encoding="utf-8"
) as f:

    blocks = json.load(f)



def compress_row(row):

    return [

        str(x).strip()

        for x in row

        if str(x).strip() != ""
    ]



def parse_matrix_state(block):

    rows = []

    for r in block["rows"]:

        c = compress_row(r)

        if c:
            rows.append(c)

    columns = None

    sections = []

    current_section = None

    for row in rows:

        # header

        if (

            len(row) > 1

            and row[0].lower() == "category"

        ):

            columns = row[1:]

            continue

        # section

        if len(row) == 1:

            current_section = {

                "name":
                    row[0],

                "columns":
                    columns,

                "rows": []
            }

            sections.append(
                current_section
            )

            continue

        # data row

        if current_section and columns:

            entry = {

                "category":
                    row[0]
            }

            for col, val in zip(

                columns,

                row[1:]
            ):

                entry[col] = val

            current_section[
                "rows"
            ].append(entry)

    return {

        "state":
            block["state"],

        "start_page":
            block["start_page"],

        "parser_type":
            "matrix",

        "sections":
            sections
    }


def parse_simple_matrix_state(block):

    rows = []

    for r in block["rows"]:

        c = compress_row(r)

        if c:
            rows.append(c)

    if len(rows) < 2:

        return {

            "state":
                block["state"],

            "start_page":
                block["start_page"],

            "parser_type":
                "simple_matrix",

            "columns": [],

            "rows": []
        }

    header = rows[0]

    columns = header[1:]

    parsed_rows = []

    for row in rows[1:]:

        entry = {

            "category":
                row[0]
        }

        for col, val in zip(

            columns,

            row[1:]
        ):

            entry[col] = val

        parsed_rows.append(
            entry
        )

    return {

        "state":
            block["state"],

        "start_page":
            block["start_page"],

        "parser_type":
            "simple_matrix",

        "columns":
            columns,

        "rows":
            parsed_rows
    }



def parse_key_value_state(block):

    rows = []

    for r in block["rows"]:

        c = compress_row(r)

        if c:
            rows.append(c)

    utility = None

    data = []

    for row in rows:

        if (

            len(row) >= 2

            and row[0].lower() == "category"

        ):

            utility = row[1]

            continue

        if len(row) >= 2:

            data.append({

                "metric":
                    row[0],

                "value":
                    row[1]
            })

    return {

        "state":
            block["state"],

        "start_page":
            block["start_page"],

        "parser_type":
            "key_value",

        "utility":
            utility,

        "data":
            data
    }



def detect_parser_type(block):

    rows = []

    for r in block["rows"]:

        c = compress_row(r)

        if c:
            rows.append(c)

    if not rows:

        return "unknown"

    header = rows[0]


    if (

        len(header) > 1

        and header[0].lower() == "category"

    ):

        # look for section rows

        for row in rows[1:]:

            if len(row) == 1:

                return "matrix"

        return "simple_matrix"

    return "key_value"



structured_states = []

for block in blocks:

    parser_type = detect_parser_type(
        block
    )

    try:

        if parser_type == "matrix":

            parsed = parse_matrix_state(
                block
            )

        elif parser_type == "simple_matrix":

            parsed = parse_simple_matrix_state(
                block
            )

        else:

            parsed = parse_key_value_state(
                block
            )

        structured_states.append(
            parsed
        )

    except Exception as e:

        structured_states.append({

            "state":
                block["state"],

            "start_page":
                block["start_page"],

            "parser_type":
                "failed",

            "error":
                str(e)
        })



with open(
    "structured_states_v2.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(

        structured_states,

        f,

        ensure_ascii=False,

        indent=2
    )



print("="*70)
print("PARSING SUMMARY")
print("="*70)

for s in structured_states:

    print(
        f"{s['state']:25s}",
        s["parser_type"]
    )

print()
print(
    "Total States:",
    len(structured_states)
)

print()
print(
    "Saved -> structured_states_v2.json"
)

======================================================================
PARSING SUMMARY
======================================================================
Andhra Pradesh            matrix
Assam                     simple_matrix
Bihar                     matrix
Chandigarh                simple_matrix
Chhattisgarh              matrix
Delhi                     matrix
Goa                       simple_matrix
Gujarat                   simple_matrix
Haryana                   simple_matrix
Himachal Pradesh          matrix
Jammu & Kashmir           simple_matrix
Jharkhand                 simple_matrix
Karnataka                 matrix
Kerala                    simple_matrix
Madhya Pradesh            simple_matrix
Maharashtra               matrix
Meghalaya                 matrix
Odisha                    simple_matrix
Puducherry                simple_matrix
Punjab                    simple_matrix
Rajasthan                 matrix
Sikkim                    simple_matrix
Tamil Nadu                simple_matrix
Telangana                 matrix
Tripura                   matrix
Uttar Pradesh             simple_matrix
Uttarakhand               simple_matrix
West Bengal               matrix

Total States: 28

Saved -> structured_states_v2.json

In [ ]:


import json

with open(
    "structured_states_v2.json",
    "r",
    encoding="utf-8"
) as f:

    data = json.load(f)

for state_name in [

    "Andhra Pradesh",
    "Assam",
    "Goa",
    "Delhi",
    "Telangana"

]:

    print("\n")
    print("="*80)
    print(state_name)
    print("="*80)

    obj = next(

        x for x in data

        if x["state"] == state_name
    )

    print(

        json.dumps(

            obj,

            indent=2,

            ensure_ascii=False

        )[:5000]
    )

================================================================================
Andhra Pradesh
================================================================================
{
  "state": "Andhra Pradesh",
  "start_page": 50,
  "parser_type": "matrix",
  "sections": [
    {
      "name": "HT Category at 11 kV",
      "columns": [
        "APSPDCL",
        "APEPDCL",
        "APCPDCL"
      ],
      "rows": [
        {
          "category": "HT I(B) Townships, Colonies, Gated\nCommunities and Villas",
          "APSPDCL": "0.97",
          "APEPDCL": "0.89",
          "APCPDCL": "1.12"
        },
        {
          "category": "HT II (A) Commercial& Others",
          "APSPDCL": "2.09",
          "APEPDCL": "2.20",
          "APCPDCL": "2.32"
        },
        {
          "category": "HT II (A) Function Halls/ Auditoriums",
          "APSPDCL": "1.99",
          "APEPDCL": "1.99",
          "APCPDCL": "1.99"
        },
        {
          "category": "HT II (B) Start-up power",
          "APSPDCL": "1.99",
          "APEPDCL": "1.99",
          "APCPDCL": "-"
        },
        {
          "category": "HT III(A) Industry",
          "APSPDCL": "1.89",
          "APEPDCL": "1.71",
          "APCPDCL": "1.85"
        },
        {
          "category": "HT III(B) Seasonal Industries (Off Season)",
          "APSPDCL": "2.38",
          "APEPDCL": "1.76",
          "APCPDCL": "1.74"
        },
        {
          "category": "HT III (C ) Energy Intensive Industries",
          "APSPDCL": "1.58",
          "APEPDCL": "-",
          "APCPDCL": "1.75"
        },
        {
          "category": "HT IV (A) Utilities (Composite Protected Water\nSupply Schemes)",
          "APSPDCL": "1.86",
          "APEPDCL": "1.91",
          "APCPDCL": "1.80"
        },
        {
          "category": "HT IV (B) General Purpose",
          "APSPDCL": "2.28",
          "APEPDCL": "2.25",
          "APCPDCL": "2.13"
        },
        {
          "category": "HT V (E ) Government/ Private Lift Irrigation",
          "APSPDCL": "-",
          "APEPDCL": "0.56",
          "APCPDCL": "0.57"
        }
      ]
    },
    {
      "name": "HT Category at 33 kV",
      "columns": [
        "APSPDCL",
        "APEPDCL",
        "APCPDCL"
      ],
      "rows": [
        {
          "category": "HT I(B) Townships, Colonies, Gated\nCommunities, Villas",
          "APSPDCL": "1.52",
          "APEPDCL": "1.47",
          "APCPDCL": "1.50"
        },
        {
          "category": "HT II(A) Commercial & Others",
          "APSPDCL": "2.28",
          "APEPDCL": "2.00",
          "APCPDCL": "1.84"
        },
        {
          "category": "HT II(B) Start up power",
          "APSPDCL": "1.99",
          "APEPDCL": "1.99",
          "APCPDCL": "1.99"
        },
        {
          "category": "HT III(A) Industry",
          "APSPDCL": "1.54",
          "APEPDCL": "1.48",
          "APCPDCL": "1.55"
        },
        {
          "category": "HT III(B) Seasonal Industries (Off Season)",
          "APSPDCL": "2.17",
          "APEPDCL": "1.53",
          "APCPDCL": "1.59"
        },
        {
          "category": "HT III(C ) Energy Intensive Industries",
          "APSPDCL": "0.36",
          "APEPDCL": "0.24",
          "APCPDCL": "-"
        },
        {
          "category": "HT IV(A) Utilities (Composite Protected Water\nSupply Schemes)",
          "APSPDCL": "1.76",
          "APEPDCL": "2.13",
          "APCPDCL": "-"
        },
        {
          "category": "HT IV(B) General Purpose",
          "APSPDCL": "1.90",
          "APEPDCL": "2.04",
          "APCPDCL": "1.74"
        },
        {
          "category": "HT V(E) Government/ Private Lift Irrigation",
          "APSPDCL": "1.25",
          "APEPDCL": "1.27",
          "APCPDCL": "1.25"
        }
      ]
    },
    {
      "name": "HT Category at 132 kV",
      "columns": [
        "APSPDCL",
        "APEPDCL",
        "APCPDCL"
      ],
      "rows": [
        {
          "category": "HT II(A) Commercial & Others",
          "APSPDCL": "1.69",
          "APEPDCL": "1.99",
          "APCPDCL": "-"
        },
        {
          "category": "HT II(B) Start Up Power",
          "APSPDCL": "1.99",
          "APEPDCL": "1.99",
          "APCPDCL": "1.99"
        },
        {
          "category": "HT III(A) Industry",
          "APSPDCL": "1.37",
          "APEPDCL": "1.44",
          "APCPDCL": "1.40"
        },
        {
          "category": "HT III(C ) Energy Intensive Industry",
          "APSPDCL": "0.31",
          "APEPDCL": "0.51",
          "APCPDCL": "-"
        },
        {
          "category": "HT IV(D) Railway Traction",
          "APSPDCL": "1.63",
          "APEPDCL": "1.59",
          "APCPDCL": "1.56"
        },
        {
          "category": "HT V (E )",
          "APSPDCL": "1.43",
          "APEPDCL": "-",
          "APCPDCL": "1.43"
        }
      ]
    },
    {
      "name": "220 kV",
      "columns": [
        "APSPDCL",
        "APEPDCL",
        "APCPDCL"
      ],
      "rows": [
        {
          "category": "HT II(A) Commercial & Others",
          "APSPDCL": "-",
          "APEPDCL": "1.66",
          "APCPDCL": "-"



================================================================================
Assam
================================================================================
{
  "state": "Assam",
  "start_page": 51,
  "parser_type": "simple_matrix",
  "columns": [
    "APDCL"
  ],
  "rows": [
    {
      "category": "HT Domestic and Commercial 30 kW & above",
      "APDCL": "1.81"
    },
    {
      "category": "Public Water Works",
      "APDCL": "1.81"
    },
    {
      "category": "Bulk Supply Govt. Edu Inst and others",
      "APDCL": "1.81"
    },
    {
      "category": "HT Small Industries up to 50 kW",
      "APDCL": "1.81"
    },
    {
      "category": "HT Industries-I 50 kW to 150 kW",
      "APDCL": "1.81"
    },
    {
      "category": "HT Industries-II above 150 kW",
      "APDCL": "1.81"
    },
    {
      "category": "Tea, Coffee, Rubber, Oil & Coal",
      "APDCL": "1.81"
    },
    {
      "category": "HT Irrigation Load above 7.5 hp",
      "APDCL": "1.81"
    },
    {
      "category": "HT Electric Crematorium & Railway Traction",
      "APDCL": "1.81"
    },
    {
      "category": "HT EV Charging Station",
      "APDCL": "1.33"
    }
  ]
}


================================================================================
Goa
================================================================================
{
  "state": "Goa",
  "start_page": 52,
  "parser_type": "simple_matrix",
  "columns": [
    "Electricity Department, Goa (EDG)"
  ],
  "rows": [
    {
      "category": "Low Tension (LT) Level",
      "Electricity Department, Goa (EDG)": "NIL"
    },
    {
      "category": "High Tension (HT)/ EHT Level",
      "Electricity Department, Goa (EDG)": "1.13"
    },
    {
      "category": "Extra High Tension (EHT) Level",
      "Electricity Department, Goa (EDG)": "0.68"
    }
  ]
}


================================================================================
Delhi
================================================================================
{
  "state": "Delhi",
  "start_page": 51,
  "parser_type": "matrix",
  "sections": [
    {
      "name": "Industrial",
      "columns": [
        "BRPL",
        "BYPL",
        "TPDDL"
      ],
      "rows": [
        {
          "category": "At LT level,11 kV/ 33kV/ 66kV & above 66kV",
          "BRPL": "1.90",
          "BYPL": "1.88",
          "TPDDL": "1.87"
        }
      ]
    },
    {
      "name": "level\nNon-Domestic",
      "columns": [
        "BRPL",
        "BYPL",
        "TPDDL"
      ],
      "rows": [
        {
          "category": "At LT level,11 kV/ 33kV/ 66kV & above 66kV",
          "BRPL": "2.24",
          "BYPL": "2.27",
          "TPDDL": "2.18"
        }
      ]
    },
    {
      "name": "DMRC & DJB",
      "columns": [
        "BRPL",
        "BYPL",
        "TPDDL"
      ],
      "rows": [
        {
          "category": "Above 66kV level",
          "BRPL": "1.47",
          "BYPL": "1.53",
          "TPDDL": "0.79"
        },
        {
          "category": "At 33/ 66kV level",
          "BRPL": "0.54",
          "BYPL": "1.29",
          "TPDDL": "0.75"
        },
        {
          "category": "At 11 kV level",
          "BRPL": "0.47",
          "BYPL": "1.23",
          "TPDDL": "0.64"
        },
        {
          "category": "At LT level",
          "BRPL": "0.03",
          "BYPL": "0.8",
          "TPDDL": "0.26"
        }
      ]
    }
  ]
}


================================================================================
Telangana
================================================================================
{
  "state": "Telangana",
  "start_page": 54,
  "parser_type": "matrix",
  "sections": [
    {
      "name": "HT Category 11 kV",
      "columns": [
        "TGSPDCL",
        "TGNPDCL"
      ],
      "rows": [
        {
          "category": "HT-I Industry General",
          "TGSPDCL": "1.98",
          "TGNPDCL": "1.99"
        },
        {
          "category": "HT-I(B)Ferro Alloys",
          "TGSPDCL": "2.04",
          "TGNPDCL": "-"
        },
        {
          "category": "HT-II(A) – Others (Commercial)",
          "TGSPDCL": "2.33",
          "TGNPDCL": "2.37"
        },
        {
          "category": "HT-II(B) – Wholly Religious Places",
          "TGSPDCL": "1.13",
          "TGNPDCL": "0.60"
        },
        {
          "category": "HT - III Airport Bus and Railway Station",
          "TGSPDCL": "2.38",
          "TGNPDCL": "2.08"
        },
        {
          "category": "HT-IV (A) Irrigation & Agriculture",
          "TGSPDCL": "1.66",
          "TGNPDCL": "1.94"
        },
        {
          "category": "HT-IV(B) CPWS Schemes",
          "TGSPDCL": "0.02",
          "TGNPDCL": "-"
        },
        {
          "category": "HT-VI Townships & Residential Colonies",
          "TGSPDCL": "1.73",
          "TGNPDCL": "1.81"
        },
        {
          "category": "HT-Temporary Supply",
          "TGSPDCL": "2.91",
          "TGNPDCL": "3.40"
        },
        {
          "category": "HT-IX EV Charging Station",
          "TGSPDCL": "0.88",
          "TGNPDCL": "-"
        }
      ]
    },
    {
      "name": "HT Category 33kV",
      "columns": [
        "TGSPDCL",
        "TGNPDCL"
      ],
      "rows": [
        {
          "category": "HT-I Industry Segregated",
          "TGSPDCL": "1.73",
          "TGNPDCL": "1.79"
        },
        {
          "category": "HT-I(B)Ferro Alloys",
          "TGSPDCL": "-",
          "TGNPDCL": "1.58"
        },
        {
          "category": "HT-II(A) – Others (Commercial)",
          "TGSPDCL": "2.04",
          "TGNPDCL": "2.12"
        },
        {
          "category": "HT-II(B) – Wholly Religious Places",
          "TGSPDCL": "0.93",
          "TGNPDCL": "-"
        },
        {
          "category": "HT-IV (A) Irrigation & Agriculture",
          "TGSPDCL": "1.70",
          "TGNPDCL": "1.80"
        },
        {
          "category": "HT-IV(B) CPWS Schemes",
          "TGSPDCL": "0.51",
          "TGNPDCL": "0.28"
        },
        {
          "category": "HT-VI Townships & Residential Colonies",
          "TGSPDCL": "1.73",
          "TGNPDCL": "1.65"
        },
        {
          "category": "HT-Temporary Supply",
          "TGSPDCL": "3.01",
          "TGNPDCL": "2.77"
        },
        {
          "category": "HT-IX EV Charging Station",
          "TGSPDCL": "2.25",
          "TGNPDCL": "0.74"
        }
      ]
    },
    {
      "name": "HT Category 132kV",
      "columns": [
        "TGSPDCL",
        "TGNPDCL"
      ],
      "rows": [
        {
          "category": "HT-I Industry",
          "TGSPDCL": "1.62",
          "TGNPDCL": "1.69"
        },
        {
          "category": "HT-I(B)Ferro Alloys",
          "TGSPDCL": "-",
          "TGNPDCL": "-"
        },
        {
          "category": "HT-II Others (Commercial)",
          "TGSPDCL": "2.34",
          "TGNPDCL": "3.77"
        },
        {
          "category": "HT-III Airports, Bus & Rly Stations",
          "TGSPDCL": "1.71",
          "TGNPDCL": "-"
        },
        {
          "category": "HT-IV(A) Irrigation & Agriculture",
          "TGSPDCL": "1.60",
          "TGNPDCL": "1.92"
        },
        {
          "category": "HT-IV(B) CPWS",
          "TGSPDCL": "0.76",
          "TGNPDCL": "0.58"
        },
        {
          "category": "HT-V(A) Railway Traction",
          "TGSPDCL": "1.34",
          "TGNPDCL": "1.01"
        },
        {
          "category": "HT-V(B)HMR",
          "TGSPDCL": "0.53",
          "TGNPDCL": "-"
        },
        {
          "category": "HT-VI Townships & Residential Colonies",
          "TGSPDCL": "-",
          "TGNPDCL": "1.74"
        }
      ]
    }
  ]
}

In [ ]:


import json
from openpyxl import Workbook
from openpyxl.styles import Font

with open(
    "structured_states_v2.json",
    "r",
    encoding="utf-8"
) as f:

    states = json.load(f)

wb = Workbook()

wb.remove(
    wb.active
)

for state in states:

    ws = wb.create_sheet(
        title=state["state"][:31]
    )

    row_ptr = 1

    ws.cell(
        row=row_ptr,
        column=1
    ).value = state["state"]

    ws.cell(
        row=row_ptr,
        column=1
    ).font = Font(
        bold=True,
        size=14
    )

    row_ptr += 2



    if state["parser_type"] == "matrix":

        for section in state["sections"]:

            ws.cell(
                row=row_ptr,
                column=1
            ).value = section["name"]

            ws.cell(
                row=row_ptr,
                column=1
            ).font = Font(
                bold=True
            )

            row_ptr += 1

            columns = (
                ["category"]
                + section["columns"]
            )

            for c_idx, col in enumerate(
                columns,
                start=1
            ):

                ws.cell(
                    row=row_ptr,
                    column=c_idx
                ).value = col

                ws.cell(
                    row=row_ptr,
                    column=c_idx
                ).font = Font(
                    bold=True
                )

            row_ptr += 1

            for record in section["rows"]:

                for c_idx, col in enumerate(
                    columns,
                    start=1
                ):

                    ws.cell(
                        row=row_ptr,
                        column=c_idx
                    ).value = record.get(
                        col,
                        ""
                    )

                row_ptr += 1

            row_ptr += 2



    elif state["parser_type"] == "simple_matrix":

        columns = (
            ["category"]
            + state["columns"]
        )

        for c_idx, col in enumerate(
            columns,
            start=1
        ):

            ws.cell(
                row=row_ptr,
                column=c_idx
            ).value = col

            ws.cell(
                row=row_ptr,
                column=c_idx
            ).font = Font(
                bold=True
            )

        row_ptr += 1

        for record in state["rows"]:

            for c_idx, col in enumerate(
                columns,
                start=1
            ):

                ws.cell(
                    row=row_ptr,
                    column=c_idx
                ).value = record.get(
                    col,
                    ""
                )

            row_ptr += 1



    elif state["parser_type"] == "key_value":

        ws.cell(
            row=row_ptr,
            column=1
        ).value = "Utility"

        ws.cell(
            row=row_ptr,
            column=2
        ).value = state.get(
            "utility",
            ""
        )

        row_ptr += 2

        ws.cell(
            row=row_ptr,
            column=1
        ).value = "Metric"

        ws.cell(
            row=row_ptr,
            column=2
        ).value = "Value"

        row_ptr += 1

        for item in state["data"]:

            ws.cell(
                row=row_ptr,
                column=1
            ).value = item["metric"]

            ws.cell(
                row=row_ptr,
                column=2
            ).value = item["value"]

            row_ptr += 1


    for column in ws.columns:

        max_len = 0

        letter = (
            column[0]
            .column_letter
        )

        for cell in column:

            try:

                max_len = max(
                    max_len,
                    len(str(cell.value))
                )

            except:
                pass

        ws.column_dimensions[
            letter
        ].width = min(
            max_len + 2,
            60
        )

wb.save(
    "Open_Access_Charges_All_States.xlsx"
)

print(
    "Saved: Open_Access_Charges_All_States.xlsx"
)

Saved: Open_Access_Charges_All_States.xlsx

In [ ]:
# import json

# with open(
#     "state_blocks_v2.json",
#     "r",
#     encoding="utf-8"
# ) as f:
#     blocks = json.load(f)

# for target in [

#     "Gujarat",
#     "Haryana",
#     "Jammu & Kashmir",
#     "Madhya Pradesh",
#     "Odisha"

# ]:

#     block = next(
#         b for b in blocks
#         if b["state"] == target
#     )

#     print("\n")
#     print("="*80)
#     print(target)
#     print("="*80)

#     for row in block["rows"][:15]:

#         compressed = [

#             str(x).strip()

#             for x in row

#             if str(x).strip() != ""
#         ]

#         print(compressed)

================================================================================
Gujarat
================================================================================
['Category', 'DGVCL', 'PGVCL', 'MGVCL', 'UGVCL']
['HT Category', '1.33', '1.33', '1.33', '1.33']


================================================================================
Haryana
================================================================================
['Category', 'UHBVNL', 'DHBVNL']
['HT Supply', '1.45', '1.45']
['Bulk Supply (other than DS)', '-', '-']
['LT Supply', '1.18', '1.18']


================================================================================
Jammu & Kashmir
================================================================================
['Category', 'JPDCL', 'KPDCL']
['HT Consumers', '1.38/kWh (or 1.24/kVAh)', '1.38/kWh (or 1.24/kVAh)']


================================================================================
Madhya Pradesh
================================================================================
['Category', 'MPMaKVVCL', 'MPPaKVV', 'MPPoKVVCL']
['LV-1: Domestic', '0.67', 'CL\n0.67', '0.67']
['LV-2 & 4: Non-Domestic & Industrial', '1.49', '1.49', '1.49']
['LV-3: Public Water Works & Street Light', '0.77', '0.77', '0.77']
['LV-6: E-Vehicle/ E-Rickshaws Charging Stations', '1.02', '1.02', '1.02']
['HV-1: Railway Traction', '1.49', '1.49', '1.49']
['HV- 2: Coal Mines', '1.49', '1.49', '1.49']
['HV- 3.1 & 3.2: Industrial and Non-Industrial', '1.49', '1.49', '1.49']
['HV- 3.3: Shopping Malls', '1.49', '1.49', '1.49']
['HV- 3.4: Power Intensive Industries', '0.90', '0.90', '0.90']
['HV- 4: Seasonal & Non-Seasonal', '1.49', '1.49', '1.49']
['HV- 5: Irrigation, Public Water Works & Other\nthan Agricultural', '1.49', '1.49', '1.49']
['HV- 6: Bulk Residential Users', '1.49', '1.49', '1.49']
['HV- 7: Synchronization and Start-Up Power', '1.49', '1.49', '1.49']
['HV- 8: EV/ E-Rickshaws Charging Stations', '1.49', '1.49', '1.49']


================================================================================
Odisha
================================================================================
['Category', 'TPCODL', 'TPNODL', 'TPSODL', 'TPWODL']
['EHT', '1.52', '1.43', '1.18', '2.50']
['HT', '0.56', '0.07', '0.17', '1.06']
['LT', '1.13', '0.34', '0.24', '1.40']

In [ ]:
# ==========================================================
# PHASE 6.1
# LOAD STRUCTURED DATA
# ==========================================================

import json
import re

# ==========================================================
# LOAD
# ==========================================================

with open(
    "structured_states_v2.json",
    "r",
    encoding="utf-8"
) as f:

    STATES = json.load(f)

# ==========================================================
# STATE LIST
# ==========================================================

STATE_NAMES = sorted(

    [x["state"] for x in STATES],

    key=len,

    reverse=True
)

# ==========================================================
# DETECT STATE
# ==========================================================

def detect_state(query):

    q = query.lower()

    for state in STATE_NAMES:

        if state.lower() in q:

            return state

    return None

# ==========================================================
# TEST
# ==========================================================

tests = [

    "Extract Andhra Pradesh Industry Charges",

    "Show Haryana LT Supply",

    "Find Goa HT Level",

    "Delhi Non Domestic",

    "Odisha EHT Charges"
]

for t in tests:

    print()
    print(t)

    print(
        "STATE:",
        detect_state(t)
    )

Extract Andhra Pradesh Industry Charges
STATE: Andhra Pradesh

Show Haryana LT Supply
STATE: Haryana

Find Goa HT Level
STATE: Goa

Delhi Non Domestic
STATE: Delhi

Odisha EHT Charges
STATE: Odisha

In [ ]:
# ==========================================================
# PHASE 6.2
# KEYWORD EXTRACTION
# ==========================================================

STOP_WORDS = {

    "extract",
    "show",
    "find",
    "get",
    "what",
    "is",
    "the",
    "charges",
    "charge",
    "open",
    "access",
    "for",
    "of",
    "in"
}

def extract_keywords(query):

    state = detect_state(query)

    q = query.lower()

    if state:

        q = q.replace(
            state.lower(),
            ""
        )

    words = re.findall(
        r"[a-zA-Z0-9]+",
        q
    )

    keywords = []

    for w in words:

        if w not in STOP_WORDS:

            keywords.append(w)

    return keywords

# ==========================================================
# TEST
# ==========================================================

tests = [

    "Extract Andhra Pradesh Industry Charges",

    "Show Haryana LT Supply",

    "Find Goa HT Level",

    "Delhi Non Domestic",

    "Odisha EHT Charges"
]

for t in tests:

    print()
    print(t)

    print(
        extract_keywords(t)
    )

Extract Andhra Pradesh Industry Charges
['industry']

Show Haryana LT Supply
['lt', 'supply']

Find Goa HT Level
['ht', 'level']

Delhi Non Domestic
['non', 'domestic']

Odisha EHT Charges
['eht']

In [ ]:
# ==========================================================
# PHASE 6.3 FINAL
# IMPROVED SEARCH ENGINE
# ==========================================================

import re

# ==========================================================
# NORMALIZATION
# ==========================================================

def normalize_text(text):

    text = str(text).lower()

    text = re.sub(
        r"[^a-z0-9]+",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()

# ==========================================================
# SCORING
# ==========================================================

def score_text(text, keywords):

    text = normalize_text(text)

    score = 0

    for kw in keywords:

        kw = normalize_text(kw)

        if kw in text:

            score += 1

    return score

# ==========================================================
# SEARCH STATE
# ==========================================================

def search_state(state_name, keywords):

    state = next(

        s for s in STATES

        if s["state"] == state_name
    )

    matches = []

    # ======================================================
    # MATRIX STATES
    # ======================================================

    if state["parser_type"] == "matrix":

        for section in state["sections"]:

            section_score = score_text(

                section["name"],

                keywords
            )

            for row in section["rows"]:

                category_score = score_text(

                    row["category"],

                    keywords
                )

                total_score = (

                    section_score
                    +
                    category_score
                )

                if total_score > 0:

                    matches.append({

                        "section":
                            section["name"],

                        "score":
                            total_score,

                        "data":
                            row
                    })

    # ======================================================
    # SIMPLE MATRIX
    # ======================================================

    elif state["parser_type"] == "simple_matrix":

        for row in state["rows"]:

            score = score_text(

                row["category"],

                keywords
            )

            if score > 0:

                matches.append({

                    "score":
                        score,

                    "data":
                        row
                })

    # ======================================================
    # KEY VALUE
    # ======================================================

    elif state["parser_type"] == "key_value":

        for row in state["data"]:

            score = score_text(

                row["metric"],

                keywords
            )

            if score > 0:

                matches.append({

                    "score":
                        score,

                    "data":
                        row
                })

    # ======================================================
    # SORT
    # ======================================================

    matches = sorted(

        matches,

        key=lambda x: x["score"],

        reverse=True
    )

    return matches

In [ ]:
# ==========================================================
# PHASE 6.4 FINAL
# QUERY ENGINE
# ==========================================================

import json

# ==========================================================
# RUN QUERY
# ==========================================================

def run_query(query):

    state = detect_state(
        query
    )

    if state is None:

        return {

            "success": False,

            "message":
                "State not detected"
        }

    keywords = extract_keywords(
        query
    )

    matches = search_state(

        state,

        keywords
    )

    return {

        "success": True,

        "query":
            query,

        "state":
            state,

        "keywords":
            keywords,

        "match_count":
            len(matches),

        "matches":
            matches[:20]
    }

# ==========================================================
# PRETTY PRINT
# ==========================================================

def answer_query(query):

    result = run_query(
        query
    )

    print()
    print("="*80)

    print(
        "QUERY:",
        query
    )

    print("="*80)

    print(
        json.dumps(
            result,
            indent=2,
            ensure_ascii=False
        )[:10000]
    )

    return result

In [ ]:
# ==========================================================
# PHASE 6.5
# RETRIEVAL TEST SUITE
# ==========================================================

queries = [

    "Extract Andhra Pradesh Industry Charges",

    "Andhra Pradesh 220 kV Industry",

    "Andhra Pradesh Railway Traction",

    "Delhi Non Domestic",

    "Delhi DMRC",

    "Telangana Ferro Alloys",

    "Goa HT Level",

    "Goa EHT Level",

    "Haryana LT Supply",

    "Odisha EHT",

    "Odisha HT",

    "Madhya Pradesh Railway Traction",

    "Punjab Bulk Supply",

    "Tamil Nadu HT Industry"
]

for q in queries:

    answer_query(q)

================================================================================
QUERY: Extract Andhra Pradesh Industry Charges
================================================================================
{
  "success": true,
  "query": "Extract Andhra Pradesh Industry Charges",
  "state": "Andhra Pradesh",
  "keywords": [
    "industry"
  ],
  "match_count": 5,
  "matches": [
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.89",
        "APEPDCL": "1.71",
        "APCPDCL": "1.85"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 1,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.54",
        "APEPDCL": "1.48",
        "APCPDCL": "1.55"
      }
    },
    {
      "section": "HT Category at 132 kV",
      "score": 1,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.37",
        "APEPDCL": "1.44",
        "APCPDCL": "1.40"
      }
    },
    {
      "section": "HT Category at 132 kV",
      "score": 1,
      "data": {
        "category": "HT III(C ) Energy Intensive Industry",
        "APSPDCL": "0.31",
        "APEPDCL": "0.51",
        "APCPDCL": "-"
      }
    },
    {
      "section": "220 kV",
      "score": 1,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.57",
        "APEPDCL": "1.37",
        "APCPDCL": "1.96"
      }
    }
  ]
}

================================================================================
QUERY: Andhra Pradesh 220 kV Industry
================================================================================
{
  "success": true,
  "query": "Andhra Pradesh 220 kV Industry",
  "state": "Andhra Pradesh",
  "keywords": [
    "220",
    "kv",
    "industry"
  ],
  "match_count": 31,
  "matches": [
    {
      "section": "220 kV",
      "score": 3,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.57",
        "APEPDCL": "1.37",
        "APCPDCL": "1.96"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.89",
        "APEPDCL": "1.71",
        "APCPDCL": "1.85"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 2,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.54",
        "APEPDCL": "1.48",
        "APCPDCL": "1.55"
      }
    },
    {
      "section": "HT Category at 132 kV",
      "score": 2,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.37",
        "APEPDCL": "1.44",
        "APCPDCL": "1.40"
      }
    },
    {
      "section": "HT Category at 132 kV",
      "score": 2,
      "data": {
        "category": "HT III(C ) Energy Intensive Industry",
        "APSPDCL": "0.31",
        "APEPDCL": "0.51",
        "APCPDCL": "-"
      }
    },
    {
      "section": "220 kV",
      "score": 2,
      "data": {
        "category": "HT II(A) Commercial & Others",
        "APSPDCL": "-",
        "APEPDCL": "1.66",
        "APCPDCL": "-"
      }
    },
    {
      "section": "220 kV",
      "score": 2,
      "data": {
        "category": "HT II(B) Start up Power",
        "APSPDCL": "1.99",
        "APEPDCL": "1.99",
        "APCPDCL": "-"
      }
    },
    {
      "section": "220 kV",
      "score": 2,
      "data": {
        "category": "HT III (C ) Energy Intensive Industries",
        "APSPDCL": "-",
        "APEPDCL": "1.57",
        "APCPDCL": "-"
      }
    },
    {
      "section": "220 kV",
      "score": 2,
      "data": {
        "category": "HT IV(D) Railway Traction",
        "APSPDCL": "1.66",
        "APEPDCL": "-",
        "APCPDCL": "-"
      }
    },
    {
      "section": "220 kV",
      "score": 2,
      "data": {
        "category": "HT V (E ) Government/ Private Lift Irrigation",
        "APSPDCL": "1.43",
        "APEPDCL": "1.43",
        "APCPDCL": "-"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT I(B) Townships, Colonies, Gated\nCommunities and Villas",
        "APSPDCL": "0.97",
        "APEPDCL": "0.89",
        "APCPDCL": "1.12"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT II (A) Commercial& Others",
        "APSPDCL": "2.09",
        "APEPDCL": "2.20",
        "APCPDCL": "2.32"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT II (A) Function Halls/ Auditoriums",
        "APSPDCL": "1.99",
        "APEPDCL": "1.99",
        "APCPDCL": "1.99"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT II (B) Start-up power",
        "APSPDCL": "1.99",
        "APEPDCL": "1.99",
        "APCPDCL": "-"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT III(B) Seasonal Industries (Off Season)",
        "APSPDCL": "2.38",
        "APEPDCL": "1.76",
        "APCPDCL": "1.74"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT III (C ) Energy Intensive Industries",
        "APSPDCL": "1.58",
        "APEPDCL": "-",
        "APCPDCL": "1.75"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT IV (A) Utilities (Composite Protected Water\nSupply Schemes)",
        "APSPDCL": "1.86",
        "APEPDCL": "1.91",
        "APCPDCL": "1.80"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT IV (B) General Purpose",
        "APSPDCL": "2.28",
        "APEPDCL": "2.25",
        "APCPDCL": "2.13"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT V (E ) Government/ Private Lift Irrigation",
        "APSPDCL": "-",
        "APEPDCL": "0.56",
        "APCPDCL": "0.57"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 1,
      "data": {
        "category": "HT I(B) Townships, Colonies, Gated\nCommunities, Villas",
        "APSPDCL": "1.52",
        "APEPDCL": "1.47",
        "APCPDCL": "1.50"
      }
    }
  ]
}

================================================================================
QUERY: Andhra Pradesh Railway Traction
================================================================================
{
  "success": true,
  "query": "Andhra Pradesh Railway Traction",
  "state": "Andhra Pradesh",
  "keywords": [
    "railway",
    "traction"
  ],
  "match_count": 2,
  "matches": [
    {
      "section": "HT Category at 132 kV",
      "score": 2,
      "data": {
        "category": "HT IV(D) Railway Traction",
        "APSPDCL": "1.63",
        "APEPDCL": "1.59",
        "APCPDCL": "1.56"
      }
    },
    {
      "section": "220 kV",
      "score": 2,
      "data": {
        "category": "HT IV(D) Railway Traction",
        "APSPDCL": "1.66",
        "APEPDCL": "-",
        "APCPDCL": "-"
      }
    }
  ]
}

================================================================================
QUERY: Delhi Non Domestic
================================================================================
{
  "success": true,
  "query": "Delhi Non Domestic",
  "state": "Delhi",
  "keywords": [
    "non",
    "domestic"
  ],
  "match_count": 1,
  "matches": [
    {
      "section": "level\nNon-Domestic",
      "score": 2,
      "data": {
        "category": "At LT level,11 kV/ 33kV/ 66kV & above 66kV",
        "BRPL": "2.24",
        "BYPL": "2.27",
        "TPDDL": "2.18"
      }
    }
  ]
}

================================================================================
QUERY: Delhi DMRC
================================================================================
{
  "success": true,
  "query": "Delhi DMRC",
  "state": "Delhi",
  "keywords": [
    "dmrc"
  ],
  "match_count": 4,
  "matches": [
    {
      "section": "DMRC & DJB",
      "score": 1,
      "data": {
        "category": "Above 66kV level",
        "BRPL": "1.47",
        "BYPL": "1.53",
        "TPDDL": "0.79"
      }
    },
    {
      "section": "DMRC & DJB",
      "score": 1,
      "data": {
        "category": "At 33/ 66kV level",
        "BRPL": "0.54",
        "BYPL": "1.29",
        "TPDDL": "0.75"
      }
    },
    {
      "section": "DMRC & DJB",
      "score": 1,
      "data": {
        "category": "At 11 kV level",
        "BRPL": "0.47",
        "BYPL": "1.23",
        "TPDDL": "0.64"
      }
    },
    {
      "section": "DMRC & DJB",
      "score": 1,
      "data": {
        "category": "At LT level",
        "BRPL": "0.03",
        "BYPL": "0.8",
        "TPDDL": "0.26"
      }
    }
  ]
}

================================================================================
QUERY: Telangana Ferro Alloys
================================================================================
{
  "success": true,
  "query": "Telangana Ferro Alloys",
  "state": "Telangana",
  "keywords": [
    "ferro",
    "alloys"
  ],
  "match_count": 3,
  "matches": [
    {
      "section": "HT Category 11 kV",
      "score": 2,
      "data": {
        "category": "HT-I(B)Ferro Alloys",
        "TGSPDCL": "2.04",
        "TGNPDCL": "-"
      }
    },
    {
      "section": "HT Category 33kV",
      "score": 2,
      "data": {
        "category": "HT-I(B)Ferro Alloys",
        "TGSPDCL": "-",
        "TGNPDCL": "1.58"
      }
    },
    {
      "section": "HT Category 132kV",
      "score": 2,
      "data": {
        "category": "HT-I(B)Ferro Alloys",
        "TGSPDCL": "-",
        "TGNPDCL": "-"
      }
    }
  ]
}

================================================================================
QUERY: Goa HT Level
================================================================================
{
  "success": true,
  "query": "Goa HT Level",
  "state": "Goa",
  "keywords": [
    "ht",
    "level"
  ],
  "match_count": 3,
  "matches": [
    {
      "score": 2,
      "data": {
        "category": "High Tension (HT)/ EHT Level",
        "Electricity Department, Goa (EDG)": "1.13"
      }
    },
    {
      "score": 2,
      "data": {
        "category": "Extra High Tension (EHT) Level",
        "Electricity Department, Goa (EDG)": "0.68"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "Low Tension (LT) Level",
        "Electricity Department, Goa (EDG)": "NIL"
      }
    }
  ]
}

================================================================================
QUERY: Goa EHT Level
================================================================================
{
  "success": true,
  "query": "Goa EHT Level",
  "state": "Goa",
  "keywords": [
    "eht",
    "level"
  ],
  "match_count": 3,
  "matches": [
    {
      "score": 2,
      "data": {
        "category": "High Tension (HT)/ EHT Level",
        "Electricity Department, Goa (EDG)": "1.13"
      }
    },
    {
      "score": 2,
      "data": {
        "category": "Extra High Tension (EHT) Level",
        "Electricity Department, Goa (EDG)": "0.68"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "Low Tension (LT) Level",
        "Electricity Department, Goa (EDG)": "NIL"
      }
    }
  ]
}

================================================================================
QUERY: Haryana LT Supply
================================================================================
{
  "success": true,
  "query": "Haryana LT Supply",
  "state": "Haryana",
  "keywords": [
    "lt",
    "supply"
  ],
  "match_count": 3,
  "matches": [
    {
      "score": 2,
      "data": {
        "category": "LT Supply",
        "UHBVNL": "1.18",
        "DHBVNL": "1.18"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "HT Supply",
        "UHBVNL": "1.45",
        "DHBVNL": "1.45"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "Bulk Supply (other than DS)",
        "UHBVNL": "-",
        "DHBVNL": "-"
      }
    }
  ]
}

================================================================================
QUERY: Odisha EHT
================================================================================
{
  "success": true,
  "query": "Odisha EHT",
  "state": "Odisha",
  "keywords": [
    "eht"
  ],
  "match_count": 1,
  "matches": [
    {
      "score": 1,
      "data": {
        "category": "EHT",
        "TPCODL": "1.52",
        "TPNODL": "1.43",
        "TPSODL": "1.18",
        "TPWODL": "2.50"
      }
    }
  ]
}

================================================================================
QUERY: Odisha HT
================================================================================
{
  "success": true,
  "query": "Odisha HT",
  "state": "Odisha",
  "keywords": [
    "ht"
  ],
  "match_count": 2,
  "matches": [
    {
      "score": 1,
      "data": {
        "category": "EHT",
        "TPCODL": "1.52",
        "TPNODL": "1.43",
        "TPSODL": "1.18",
        "TPWODL": "2.50"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "HT",
        "TPCODL": "0.56",
        "TPNODL": "0.07",
        "TPSODL": "0.17",
        "TPWODL": "1.06"
      }
    }
  ]
}

================================================================================
QUERY: Madhya Pradesh Railway Traction
================================================================================
{
  "success": true,
  "query": "Madhya Pradesh Railway Traction",
  "state": "Madhya Pradesh",
  "keywords": [
    "railway",
    "traction"
  ],
  "match_count": 1,
  "matches": [
    {
      "score": 2,
      "data": {
        "category": "HV-1: Railway Traction",
        "MPMaKVVCL": "1.49",
        "MPPaKVV": "1.49",
        "MPPoKVVCL": "1.49"
      }
    }
  ]
}

================================================================================
QUERY: Punjab Bulk Supply
================================================================================
{
  "success": true,
  "query": "Punjab Bulk Supply",
  "state": "Punjab",
  "keywords": [
    "bulk",
    "supply"
  ],
  "match_count": 3,
  "matches": [
    {
      "score": 2,
      "data": {
        "category": "Bulk Supply",
        "PSPCL": "1.22"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "Large Supply",
        "PSPCL": "0.86"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "Non-Residential Supply",
        "PSPCL": "1.22"
      }
    }
  ]
}

================================================================================
QUERY: Tamil Nadu HT Industry
================================================================================
{
  "success": true,
  "query": "Tamil Nadu HT Industry",
  "state": "Tamil Nadu",
  "keywords": [
    "ht",
    "industry"
  ],
  "match_count": 5,
  "matches": [
    {
      "score": 2,
      "data": {
        "category": "HTI A: HT-Industry",
        "TANGEDCO": "1.99"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "HT II A: Govt. educational institute",
        "TANGEDCO": "2.19"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "HT II B: Pvt Educational Institute",
        "TANGEDCO": "2.46"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "HT III & V – HT Miscellaneous / EV charging",
        "TANGEDCO": "2.57"
      }
    },
    {
      "score": 1,
      "data": {
        "category": "HT IV - Temporary Supply",
        "TANGEDCO": "3.50"
      }
    }
  ]
}

In [ ]:
while True:

    q = input(
        "\nEnter Query (or exit): "
    )

    if q.lower() == "exit":

        break

    answer_query(q)

Enter Query (or exit): Karnataka Industry Rate

================================================================================
QUERY: Karnataka Industry Rate
================================================================================
{
  "success": true,
  "query": "Karnataka Industry Rate",
  "state": "Karnataka",
  "keywords": [
    "industry",
    "rate"
  ],
  "match_count": 0,
  "matches": []
}

Enter Query (or exit): Karnataka Industry

================================================================================
QUERY: Karnataka Industry
================================================================================
{
  "success": true,
  "query": "Karnataka Industry",
  "state": "Karnataka",
  "keywords": [
    "industry"
  ],
  "match_count": 0,
  "matches": []
}

Enter Query (or exit): Tamil Nadu Industry

================================================================================
QUERY: Tamil Nadu Industry
================================================================================
{
  "success": true,
  "query": "Tamil Nadu Industry",
  "state": "Tamil Nadu",
  "keywords": [
    "industry"
  ],
  "match_count": 1,
  "matches": [
    {
      "score": 1,
      "data": {
        "category": "HTI A: HT-Industry",
        "TANGEDCO": "1.99"
      }
    }
  ]
}

Enter Query (or exit): Delhi Non Domestic

================================================================================
QUERY: Delhi Non Domestic
================================================================================
{
  "success": true,
  "query": "Delhi Non Domestic",
  "state": "Delhi",
  "keywords": [
    "non",
    "domestic"
  ],
  "match_count": 1,
  "matches": [
    {
      "section": "level\nNon-Domestic",
      "score": 2,
      "data": {
        "category": "At LT level,11 kV/ 33kV/ 66kV & above 66kV",
        "BRPL": "2.24",
        "BYPL": "2.27",
        "TPDDL": "2.18"
      }
    }
  ]
}

Enter Query (or exit): Andhra 11 KW

================================================================================
QUERY: Andhra 11 KW
================================================================================
{
  "success": false,
  "message": "State not detected"
}

Enter Query (or exit): Andhra Pradesh 11 KW

================================================================================
QUERY: Andhra Pradesh 11 KW
================================================================================
{
  "success": true,
  "query": "Andhra Pradesh 11 KW",
  "state": "Andhra Pradesh",
  "keywords": [
    "11",
    "kw"
  ],
  "match_count": 10,
  "matches": [
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT I(B) Townships, Colonies, Gated\nCommunities and Villas",
        "APSPDCL": "0.97",
        "APEPDCL": "0.89",
        "APCPDCL": "1.12"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT II (A) Commercial& Others",
        "APSPDCL": "2.09",
        "APEPDCL": "2.20",
        "APCPDCL": "2.32"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT II (A) Function Halls/ Auditoriums",
        "APSPDCL": "1.99",
        "APEPDCL": "1.99",
        "APCPDCL": "1.99"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT II (B) Start-up power",
        "APSPDCL": "1.99",
        "APEPDCL": "1.99",
        "APCPDCL": "-"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.89",
        "APEPDCL": "1.71",
        "APCPDCL": "1.85"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT III(B) Seasonal Industries (Off Season)",
        "APSPDCL": "2.38",
        "APEPDCL": "1.76",
        "APCPDCL": "1.74"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT III (C ) Energy Intensive Industries",
        "APSPDCL": "1.58",
        "APEPDCL": "-",
        "APCPDCL": "1.75"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT IV (A) Utilities (Composite Protected Water\nSupply Schemes)",
        "APSPDCL": "1.86",
        "APEPDCL": "1.91",
        "APCPDCL": "1.80"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT IV (B) General Purpose",
        "APSPDCL": "2.28",
        "APEPDCL": "2.25",
        "APCPDCL": "2.13"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 1,
      "data": {
        "category": "HT V (E ) Government/ Private Lift Irrigation",
        "APSPDCL": "-",
        "APEPDCL": "0.56",
        "APCPDCL": "0.57"
      }
    }
  ]
}

Enter Query (or exit): Andhra Pradesh 11 KV Industrial Commercial

================================================================================
QUERY: Andhra Pradesh 11 KV Industrial Commercial
================================================================================
{
  "success": true,
  "query": "Andhra Pradesh 11 KV Industrial Commercial",
  "state": "Andhra Pradesh",
  "keywords": [
    "11",
    "kv",
    "industrial",
    "commercial"
  ],
  "match_count": 31,
  "matches": [
    {
      "section": "HT Category at 11 kV",
      "score": 3,
      "data": {
        "category": "HT II (A) Commercial& Others",
        "APSPDCL": "2.09",
        "APEPDCL": "2.20",
        "APCPDCL": "2.32"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT I(B) Townships, Colonies, Gated\nCommunities and Villas",
        "APSPDCL": "0.97",
        "APEPDCL": "0.89",
        "APCPDCL": "1.12"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT II (A) Function Halls/ Auditoriums",
        "APSPDCL": "1.99",
        "APEPDCL": "1.99",
        "APCPDCL": "1.99"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT II (B) Start-up power",
        "APSPDCL": "1.99",
        "APEPDCL": "1.99",
        "APCPDCL": "-"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.89",
        "APEPDCL": "1.71",
        "APCPDCL": "1.85"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT III(B) Seasonal Industries (Off Season)",
        "APSPDCL": "2.38",
        "APEPDCL": "1.76",
        "APCPDCL": "1.74"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT III (C ) Energy Intensive Industries",
        "APSPDCL": "1.58",
        "APEPDCL": "-",
        "APCPDCL": "1.75"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT IV (A) Utilities (Composite Protected Water\nSupply Schemes)",
        "APSPDCL": "1.86",
        "APEPDCL": "1.91",
        "APCPDCL": "1.80"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT IV (B) General Purpose",
        "APSPDCL": "2.28",
        "APEPDCL": "2.25",
        "APCPDCL": "2.13"
      }
    },
    {
      "section": "HT Category at 11 kV",
      "score": 2,
      "data": {
        "category": "HT V (E ) Government/ Private Lift Irrigation",
        "APSPDCL": "-",
        "APEPDCL": "0.56",
        "APCPDCL": "0.57"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 2,
      "data": {
        "category": "HT II(A) Commercial & Others",
        "APSPDCL": "2.28",
        "APEPDCL": "2.00",
        "APCPDCL": "1.84"
      }
    },
    {
      "section": "HT Category at 132 kV",
      "score": 2,
      "data": {
        "category": "HT II(A) Commercial & Others",
        "APSPDCL": "1.69",
        "APEPDCL": "1.99",
        "APCPDCL": "-"
      }
    },
    {
      "section": "220 kV",
      "score": 2,
      "data": {
        "category": "HT II(A) Commercial & Others",
        "APSPDCL": "-",
        "APEPDCL": "1.66",
        "APCPDCL": "-"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 1,
      "data": {
        "category": "HT I(B) Townships, Colonies, Gated\nCommunities, Villas",
        "APSPDCL": "1.52",
        "APEPDCL": "1.47",
        "APCPDCL": "1.50"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 1,
      "data": {
        "category": "HT II(B) Start up power",
        "APSPDCL": "1.99",
        "APEPDCL": "1.99",
        "APCPDCL": "1.99"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 1,
      "data": {
        "category": "HT III(A) Industry",
        "APSPDCL": "1.54",
        "APEPDCL": "1.48",
        "APCPDCL": "1.55"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 1,
      "data": {
        "category": "HT III(B) Seasonal Industries (Off Season)",
        "APSPDCL": "2.17",
        "APEPDCL": "1.53",
        "APCPDCL": "1.59"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 1,
      "data": {
        "category": "HT III(C ) Energy Intensive Industries",
        "APSPDCL": "0.36",
        "APEPDCL": "0.24",
        "APCPDCL": "-"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 1,
      "data": {
        "category": "HT IV(A) Utilities (Composite Protected Water\nSupply Schemes)",
        "APSPDCL": "1.76",
        "APEPDCL": "2.13",
        "APCPDCL": "-"
      }
    },
    {
      "section": "HT Category at 33 kV",
      "score": 1,
      "data": {
        "category": "HT IV(B) General Purpose",
        "APSPDCL": "1.90",
        "APEPDCL": "2.04",
        "APCPDCL": "1.74"
      }
    }
  ]
}

Enter Query (or exit): exit